#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Figure 4 Q75 panel: pooled medial+lateral birds, using the EXACT syllable
selection generated by the Figure 3 quantile analysis.

Selection source
----------------
The script reads Figure 3's:
    syllable_level_quantile_selection.csv

and uses:
    selected_Q75 == True   ->  >= Q75 delta-CV syllables
    selected_Q75 == False  ->  < Q75 delta-CV syllables

The BC table is INNER-MERGED to the complete Figure 3 qualifying-syllable
table. Therefore, the below-Q75 comparison group does NOT accidentally include
syllables that failed Figure 3's phrase-duration eligibility criteria.

Within each pooled medial+lateral bird and subset, the script takes the median
BC across BC-qualified syllables, then compares Post vs Pre across birds.
Each subset test uses all birds with valid BC for that subset; only the direct
Q75-vs-below-Q75 contrast requires both subsets in the same bird.

Displayed tests:
    - >= Q75 delta-CV syllables: raw two-sided paired Wilcoxon
    - < Q75 delta-CV syllables:  raw two-sided paired Wilcoxon

Additional one-sided, Holm-adjusted, exact sign-flip, bootstrap-CI, and direct
selected-vs-below-Q75 delta-BC contrast results are written to output tables.

Figure labels use the manuscript-facing notation:
    >= Q75 ΔCV syllables
    < Q75 ΔCV syllables
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Any, Iterable, Optional

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

try:
    from scipy import stats as scipy_stats
except Exception:
    scipy_stats = None


SHAM = "sham saline injection"
LATERAL = "Lateral lesion only"
COMPLETE_ML = "Complete Medial and Lateral lesion"
PARTIAL_ML = "Partial Medial and Lateral lesion"
POOLED_ML = "Complete and partial medial and lateral lesion"
UNKNOWN = "unknown"

# Match the updated Figure 3 palette.
FIG3_POOLED_ML_PURPLE = "#7A4FB7"


def norm_text(x: Any) -> str:
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return ""
    return " ".join(str(x).strip().split()).lower()


def normalize_syllable_token(x: Any) -> str:
    """Normalize labels so numeric tokens such as 3, 3.0, and '3.0' match."""
    if x is None or pd.isna(x):
        return ""
    s = str(x).strip()
    if not s:
        return ""

    # Spreadsheet/CSV parsing often turns integer labels into strings like
    # "3.0". Convert only values that are exactly integer-like numerics.
    if re.fullmatch(r"[+-]?\d+(?:\.0+)?", s):
        try:
            return str(int(float(s)))
        except ValueError:
            pass

    return s


def first_present(columns: Iterable[str], candidates: list[str]) -> Optional[str]:
    lookup = {norm_text(c): c for c in columns}
    for candidate in candidates:
        hit = lookup.get(norm_text(candidate))
        if hit is not None:
            return hit
    return None


def canonical_group(raw: Any) -> str:
    s = norm_text(raw)
    if not s:
        return UNKNOWN
    if "sham" in s or ("saline" in s and "lesion" not in s):
        return SHAM
    if "lateral lesion only" in s or "lateral only" in s or "single hit" in s:
        return LATERAL
    if "complete and partial" in s and "medial" in s and "lateral" in s:
        return POOLED_ML
    if "complete" in s and "medial" in s and "lateral" in s:
        return COMPLETE_ML
    if "partial" in s and "medial" in s and "lateral" in s:
        return PARTIAL_ML
    if "area x not visible" in s or ("large" in s and "lesion" in s):
        return COMPLETE_ML
    if ("medial" in s and "lateral" in s) or "m+l" in s:
        return PARTIAL_ML
    return str(raw)


def pooled_group(group: str) -> str:
    return POOLED_ML if group in {COMPLETE_ML, PARTIAL_ML, POOLED_ML} else group


def read_metadata_map(path: Optional[str]) -> dict[str, str]:
    if not path:
        return {}
    workbook = Path(path)
    if not workbook.exists():
        raise FileNotFoundError(workbook)

    animal_candidates = ["Animal ID", "animal_id", "bird_id", "bird"]
    hit_candidates = [
        "Lesion hit type",
        "lesion_hit_type",
        "Hit type",
        "hit_type",
        "raw_lesion_hit_type",
    ]
    xls = pd.ExcelFile(workbook)
    for sheet in xls.sheet_names:
        table = pd.read_excel(workbook, sheet_name=sheet)
        animal_col = first_present(table.columns, animal_candidates)
        hit_col = first_present(table.columns, hit_candidates)
        if animal_col and hit_col:
            return {
                str(animal).strip(): str(hit).strip()
                for animal, hit in zip(table[animal_col], table[hit_col])
                if pd.notna(animal) and pd.notna(hit)
            }
    raise ValueError(f"Could not find animal and lesion-hit-type columns in {workbook}")


def read_quantile_selection(
    path: str,
    selection_column: str = "selected_Q75",
) -> pd.DataFrame:
    """
    Read the full Figure 3 syllable-level quantile-selection CSV.

    Expected input:
        syllable_level_quantile_selection.csv

    The table must contain:
        - animal_id (or equivalent)
        - syllable / cluster identifier
        - a boolean selection column such as selected_Q75

    IMPORTANT:
    Both selected and nonselected Figure 3 syllables are retained. Figure 4
    later INNER-MERGES this table with the BC table, so the "< Q75" subset
    contains only syllables that were part of the Figure 3 qualifying set,
    rather than every other syllable that happens to have BC data.
    """
    csv_path = Path(path)
    if not csv_path.exists():
        raise FileNotFoundError(csv_path)

    table = pd.read_csv(csv_path)

    animal_col = first_present(
        table.columns,
        ["animal_id", "Animal ID", "bird_id", "bird"],
    )
    syllable_col = first_present(
        table.columns,
        [
            "syllable",
            "Syllable",
            "label",
            "cluster",
            "cluster_id",
            "cluster_token",
            "cluster_label",
            "syllable_cluster",
        ],
    )
    flag_col = first_present(table.columns, [selection_column])

    if animal_col is None or syllable_col is None or flag_col is None:
        raise ValueError(
            "Figure 3 quantile-selection CSV must contain animal, syllable/cluster, "
            f"and {selection_column!r} columns. Found: {list(table.columns)}"
        )

    out = table[[animal_col, syllable_col, flag_col]].copy()
    out.columns = ["animal_id", "syllable", "selection_flag_raw"]

    out["animal_id"] = out["animal_id"].astype(str).str.strip()
    out["syllable"] = out["syllable"].map(normalize_syllable_token)

    raw = out["selection_flag_raw"]
    if pd.api.types.is_bool_dtype(raw):
        parsed = raw.astype(bool)
    else:
        normalized = raw.astype(str).str.strip().str.lower()
        true_values = {"true", "1", "yes", "y", "t"}
        false_values = {"false", "0", "no", "n", "f"}
        bad = ~normalized.isin(true_values | false_values)
        if bad.any():
            examples = raw[bad].drop_duplicates().head(12).tolist()
            raise ValueError(
                f"Could not parse {selection_column!r} as boolean. "
                f"Unrecognized values include: {examples}"
            )
        parsed = normalized.isin(true_values)

    out["is_q75"] = parsed.to_numpy(dtype=bool)
    out = out[(out["animal_id"] != "") & (out["syllable"] != "")].copy()

    # Guard against duplicated animal x syllable rows with conflicting flags.
    conflicts = (
        out.groupby(["animal_id", "syllable"])["is_q75"]
        .nunique()
        .reset_index(name="n_unique_flags")
    )
    conflicts = conflicts[conflicts["n_unique_flags"] > 1]
    if not conflicts.empty:
        raise ValueError(
            "Conflicting Q75 selection flags were found for duplicated "
            "animal x syllable pairs. Examples:\n"
            f"{conflicts.head(12).to_string(index=False)}"
        )

    out = (
        out[["animal_id", "syllable", "is_q75"]]
        .drop_duplicates()
        .reset_index(drop=True)
    )

    print(
        f"[INFO] Figure 3 qualifying pairs: {len(out)} across "
        f"{out['animal_id'].nunique()} birds"
    )
    print(
        f"[INFO] {selection_column}=True: {int(out['is_q75'].sum())} pairs; "
        f"False: {int((~out['is_q75']).sum())} pairs"
    )
    return out



def choose_bc_syllable_column(
    table: pd.DataFrame,
    animal_col: str,
    selected_pairs: pd.DataFrame,
) -> tuple[str, pd.DataFrame]:
    """Choose the BC label column that actually matches the selected-pairs CSV."""
    candidates = [
        "cluster_token",
        "syllable",
        "Syllable",
        "label",
        "cluster_label",
        "syllable_cluster",
        "cluster",
        "cluster_id",
    ]
    present = [c for c in candidates if c in table.columns]
    if not present:
        raise ValueError(
            "No syllable/cluster identifier column was found in the BC table. "
            f"Found: {list(table.columns)}"
        )

    selected_keys = selected_pairs[["animal_id", "syllable"]].drop_duplicates()
    reports = []
    for column in present:
        candidate = pd.DataFrame(
            {
                "animal_id": table[animal_col].astype(str).str.strip(),
                "syllable": table[column].map(normalize_syllable_token),
            }
        ).drop_duplicates()
        candidate = candidate[
            (candidate["animal_id"] != "") & (candidate["syllable"] != "")
        ]
        matched = selected_keys.merge(
            candidate,
            on=["animal_id", "syllable"],
            how="inner",
        )
        reports.append(
            {
                "candidate_column": column,
                "matched_selected_pairs": int(len(matched)),
                "matched_birds": int(matched["animal_id"].nunique()),
                "available_unique_pairs": int(len(candidate)),
            }
        )

    report = pd.DataFrame(reports).sort_values(
        ["matched_selected_pairs", "matched_birds"],
        ascending=False,
        kind="stable",
    )
    for row in report.itertuples(index=False):
        print(
            "[INFO] BC label candidate "
            f"{row.candidate_column!r}: "
            f"{row.matched_selected_pairs}/{len(selected_keys)} selected pairs "
            f"matched across {row.matched_birds} birds"
        )

    best = report.iloc[0]
    if int(best["matched_selected_pairs"]) == 0:
        selected_example = selected_keys.head(12).to_dict("records")
        bc_examples = {}
        for column in present:
            values = (
                table[column]
                .map(normalize_syllable_token)
                .loc[lambda s: s != ""]
                .drop_duplicates()
                .head(12)
                .tolist()
            )
            bc_examples[column] = values
        raise ValueError(
            "None of the BC identifier columns matched the selected-pairs CSV, "
            "even after normalizing integer-like labels such as 3.0 to 3.\n"
            f"Selected-pair examples: {selected_example}\n"
            f"BC identifier examples: {bc_examples}"
        )

    chosen = str(best["candidate_column"])
    print(f"[OK] Using BC syllable identifier column: {chosen}")
    return chosen, report.reset_index(drop=True)


def read_bc_table(
    path: str,
    metadata_excel: Optional[str],
    selected_pairs: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    csv_path = Path(path)
    if not csv_path.exists():
        raise FileNotFoundError(csv_path)
    table = pd.read_csv(csv_path)
    print(f"[INFO] BC input columns: {list(table.columns)}")

    animal_col = first_present(table.columns, ["animal_id", "Animal ID", "bird_id", "bird"])
    if animal_col is None:
        raise ValueError(
            "BC CSV must contain an animal/bird identifier column. "
            f"Found: {list(table.columns)}"
        )
    syllable_col, identifier_report = choose_bc_syllable_column(
        table,
        animal_col,
        selected_pairs,
    )
    pre_col = first_present(
        table.columns,
        ["bc_pre", "pre_bc", "Pre BC", "median_pre_bc", "pre_bhattacharyya_coefficient"],
    )
    post_col = first_present(
        table.columns,
        ["bc_post", "post_bc", "Post BC", "median_post_bc", "post_bhattacharyya_coefficient"],
    )
    if pre_col is None or post_col is None:
        raise ValueError(
            "BC CSV must contain animal, syllable/cluster, pre-BC, and post-BC columns. "
            f"Found: {list(table.columns)}"
        )

    out = table.copy()
    out["animal_id"] = out[animal_col].astype(str).str.strip()
    out["syllable_source_column"] = syllable_col
    out["syllable_raw"] = out[syllable_col]
    out["syllable"] = out[syllable_col].map(normalize_syllable_token)
    out["pre_bc"] = pd.to_numeric(out[pre_col], errors="coerce")
    out["post_bc"] = pd.to_numeric(out[post_col], errors="coerce")
    out["delta_bc"] = out["post_bc"] - out["pre_bc"]

    group_col = first_present(
        out.columns,
        [
            "lesion_group_detailed",
            "display_group",
            "lesion_group",
            "lesion_hit_type",
            "raw_lesion_hit_type",
            "raw_hit_type",
            "group_label",
        ],
    )
    metadata_map = read_metadata_map(metadata_excel)
    if group_col is not None:
        out["detailed_group"] = out[group_col].map(canonical_group)
    else:
        out["detailed_group"] = UNKNOWN
    if metadata_map:
        from_workbook = out["animal_id"].map(metadata_map)
        out.loc[from_workbook.notna(), "detailed_group"] = from_workbook[from_workbook.notna()].map(canonical_group)

    out["pooled_group"] = out["detailed_group"].map(pooled_group)
    out = out.dropna(subset=["pre_bc", "post_bc"]).copy()
    out = out[(out["animal_id"] != "") & (out["syllable"] != "")].copy()
    return out.reset_index(drop=True), identifier_report


def exact_signflip_p(differences: np.ndarray, alternative: str) -> tuple[float, int]:
    differences = np.asarray(differences, dtype=float)
    differences = differences[np.isfinite(differences)]
    n = len(differences)
    if n == 0:
        return np.nan, 0

    observed = float(np.mean(differences))
    if n <= 20:
        total = 1 << n
        null_values = np.empty(total, dtype=float)
        for mask in range(total):
            signs = np.array([1.0 if (mask >> i) & 1 else -1.0 for i in range(n)])
            null_values[mask] = np.mean(differences * signs)
    else:
        total = 100_000
        rng = np.random.default_rng(123)
        signs = rng.choice([-1.0, 1.0], size=(total, n))
        null_values = np.mean(signs * differences[None, :], axis=1)

    if alternative == "less":
        p = np.mean(null_values <= observed + 1e-12)
    elif alternative == "greater":
        p = np.mean(null_values >= observed - 1e-12)
    else:
        p = np.mean(np.abs(null_values) >= abs(observed) - 1e-12)
    return float(p), int(total)


def paired_wilcoxon(
    pre: np.ndarray,
    post: np.ndarray,
    alternative: str = "two-sided",
) -> float:
    pre = np.asarray(pre, dtype=float)
    post = np.asarray(post, dtype=float)
    mask = np.isfinite(pre) & np.isfinite(post)
    pre = pre[mask]
    post = post[mask]
    if len(pre) == 0 or scipy_stats is None:
        return np.nan
    try:
        # scipy compares the first array with the second. Thus
        # alternative="less" tests post < pre.
        return float(
            scipy_stats.wilcoxon(
                post,
                pre,
                alternative=alternative,
                zero_method="wilcox",
                method="auto",
            ).pvalue
        )
    except Exception:
        return np.nan


def holm_adjust(p_values: list[float]) -> list[float]:
    p = np.asarray(p_values, dtype=float)
    adjusted = np.full_like(p, np.nan)
    valid = np.where(np.isfinite(p))[0]
    if len(valid) == 0:
        return adjusted.tolist()

    order = valid[np.argsort(p[valid])]
    running = 0.0
    m = len(valid)
    for rank, idx in enumerate(order):
        candidate = min(1.0, (m - rank) * p[idx])
        running = max(running, candidate)
        adjusted[idx] = running
    return adjusted.tolist()


def bootstrap_mean_ci(values: np.ndarray, reps: int = 10_000, seed: int = 456) -> tuple[float, float]:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if len(values) == 0:
        return np.nan, np.nan
    rng = np.random.default_rng(seed)
    estimates = np.empty(reps, dtype=float)
    for i in range(reps):
        estimates[i] = np.mean(rng.choice(values, size=len(values), replace=True))
    return float(np.percentile(estimates, 2.5)), float(np.percentile(estimates, 97.5))


def p_label(p: float) -> str:
    if not np.isfinite(p):
        return "n.s."
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    return "n.s."


def make_bird_table(merged: pd.DataFrame) -> pd.DataFrame:
    """
    Create one Pre/Post BC value per bird for each Q75 subset.

    IMPORTANT:
    Birds are retained if they have valid BC data in EITHER subset. The
    within-subset Pre-vs-Post tests therefore use all birds available for that
    subset. Only the direct >=Q75-vs-below-Q75 delta-BC contrast later requires
    a bird to have data in both subsets.
    """
    ml = merged[merged["pooled_group"] == POOLED_ML].copy()

    grouped = (
        ml.groupby(["animal_id", "subset"], dropna=False)
        .agg(
            n_syllables=("syllable", "nunique"),
            pre_bc=("pre_bc", "median"),
            post_bc=("post_bc", "median"),
        )
        .reset_index()
    )
    grouped["delta_bc"] = grouped["post_bc"] - grouped["pre_bc"]

    wide = grouped.pivot(index="animal_id", columns="subset")
    wide.columns = [
        "_".join(map(str, col)).strip("_")
        for col in wide.columns.to_flat_index()
    ]
    wide = wide.reset_index().rename(
        columns={
            "n_syllables_q75_or_above": "q75_n_syllables",
            "pre_bc_q75_or_above": "q75_pre_bc",
            "post_bc_q75_or_above": "q75_post_bc",
            "delta_bc_q75_or_above": "q75_delta_bc",
            "n_syllables_below_q75": "below_q75_n_syllables",
            "pre_bc_below_q75": "below_q75_pre_bc",
            "post_bc_below_q75": "below_q75_post_bc",
            "delta_bc_below_q75": "below_q75_delta_bc",
        }
    )

    # Ensure expected columns exist even when one subset is absent for some birds.
    for col in [
        "q75_n_syllables",
        "q75_pre_bc",
        "q75_post_bc",
        "q75_delta_bc",
        "below_q75_n_syllables",
        "below_q75_pre_bc",
        "below_q75_post_bc",
        "below_q75_delta_bc",
    ]:
        if col not in wide.columns:
            wide[col] = np.nan

    wide["q75_delta_bc"] = wide["q75_post_bc"] - wide["q75_pre_bc"]
    wide["below_q75_delta_bc"] = (
        wide["below_q75_post_bc"] - wide["below_q75_pre_bc"]
    )
    wide["q75_minus_below_delta_bc"] = (
        wide["q75_delta_bc"] - wide["below_q75_delta_bc"]
    )

    n_q75 = int(
        np.sum(
            np.isfinite(wide["q75_pre_bc"].to_numpy(float))
            & np.isfinite(wide["q75_post_bc"].to_numpy(float))
        )
    )
    n_below = int(
        np.sum(
            np.isfinite(wide["below_q75_pre_bc"].to_numpy(float))
            & np.isfinite(wide["below_q75_post_bc"].to_numpy(float))
        )
    )
    n_both = int(
        np.sum(
            np.isfinite(wide["q75_delta_bc"].to_numpy(float))
            & np.isfinite(wide["below_q75_delta_bc"].to_numpy(float))
        )
    )

    print(f"[INFO] Pooled M+L birds with >=Q75 BC: {n_q75}")
    print(f"[INFO] Pooled M+L birds with below-Q75 BC: {n_below}")
    print(f"[INFO] Pooled M+L birds with BOTH subsets: {n_both}")

    return wide



def run_tests(by_bird: pd.DataFrame) -> pd.DataFrame:
    """
    Run each subset's Pre-vs-Post test using all birds available for that
    subset. The direct subset contrast uses only birds with both subsets.
    """
    rows: list[dict[str, Any]] = []

    for subset_label, pre_col, post_col in [
        (">= Q75 ΔCV syllables", "q75_pre_bc", "q75_post_bc"),
        ("< Q75 ΔCV syllables", "below_q75_pre_bc", "below_q75_post_bc"),
    ]:
        pre_all = by_bird[pre_col].to_numpy(dtype=float)
        post_all = by_bird[post_col].to_numpy(dtype=float)
        mask = np.isfinite(pre_all) & np.isfinite(post_all)
        pre = pre_all[mask]
        post = post_all[mask]

        if len(pre) == 0:
            raise ValueError(f"No valid paired BC values for {subset_label}")

        diff = post - pre

        signflip_one_sided_p, n_permutations = exact_signflip_p(
            diff, alternative="less"
        )
        signflip_two_sided_p, _ = exact_signflip_p(
            diff, alternative="two-sided"
        )
        wilcoxon_one_sided_p = paired_wilcoxon(
            pre, post, alternative="less"
        )
        wilcoxon_two_sided_p = paired_wilcoxon(
            pre, post, alternative="two-sided"
        )
        ci_low, ci_high = bootstrap_mean_ci(diff)

        rows.append(
            {
                "comparison": f"{subset_label}: Pre vs Post",
                "subset": subset_label,
                "n_birds": len(diff),
                "median_pre_bc": float(np.median(pre)),
                "median_post_bc": float(np.median(post)),
                "median_delta_bc_post_minus_pre": float(np.median(diff)),
                "mean_delta_bc_post_minus_pre": float(np.mean(diff)),
                "mean_delta_bootstrap_ci_low": ci_low,
                "mean_delta_bootstrap_ci_high": ci_high,
                "wilcoxon_two_sided_p": wilcoxon_two_sided_p,
                "wilcoxon_one_sided_p_post_less_pre": wilcoxon_one_sided_p,
                "signflip_two_sided_p": signflip_two_sided_p,
                "signflip_one_sided_p_post_less_pre": signflip_one_sided_p,
                "n_signflip_permutations": n_permutations,
            }
        )

    tests = pd.DataFrame(rows)
    tests["wilcoxon_two_sided_holm_p"] = holm_adjust(
        tests["wilcoxon_two_sided_p"].tolist()
    )
    tests["wilcoxon_one_sided_holm_p"] = holm_adjust(
        tests["wilcoxon_one_sided_p_post_less_pre"].tolist()
    )
    tests["signflip_two_sided_holm_p"] = holm_adjust(
        tests["signflip_two_sided_p"].tolist()
    )
    tests["signflip_one_sided_holm_p"] = holm_adjust(
        tests["signflip_one_sided_p_post_less_pre"].tolist()
    )

    # Direct within-bird test requires BOTH subsets.
    q75_delta = by_bird["q75_delta_bc"].to_numpy(dtype=float)
    below_delta = by_bird["below_q75_delta_bc"].to_numpy(dtype=float)
    interaction_mask = np.isfinite(q75_delta) & np.isfinite(below_delta)
    interaction = q75_delta[interaction_mask] - below_delta[interaction_mask]

    if len(interaction) > 0:
        interaction_p, n_permutations = exact_signflip_p(
            interaction, alternative="less"
        )
        ci_low, ci_high = bootstrap_mean_ci(interaction)

        interaction_two_sided_w = paired_wilcoxon(
            below_delta[interaction_mask],
            q75_delta[interaction_mask],
            alternative="two-sided",
        )
        interaction_one_sided_w = paired_wilcoxon(
            below_delta[interaction_mask],
            q75_delta[interaction_mask],
            alternative="less",
        )
        interaction_two_sided_sf = exact_signflip_p(
            interaction, alternative="two-sided"
        )[0]
    else:
        interaction_p = np.nan
        n_permutations = 0
        ci_low = ci_high = np.nan
        interaction_two_sided_w = np.nan
        interaction_one_sided_w = np.nan
        interaction_two_sided_sf = np.nan

    interaction_row = pd.DataFrame(
        [
            {
                "comparison": ">= Q75 ΔCV deltaBC < below-Q75 deltaBC",
                "subset": "DeltaBC contrast",
                "n_birds": len(interaction),
                "median_pre_bc": np.nan,
                "median_post_bc": np.nan,
                "median_delta_bc_post_minus_pre": (
                    float(np.median(interaction)) if len(interaction) else np.nan
                ),
                "mean_delta_bc_post_minus_pre": (
                    float(np.mean(interaction)) if len(interaction) else np.nan
                ),
                "mean_delta_bootstrap_ci_low": ci_low,
                "mean_delta_bootstrap_ci_high": ci_high,
                "wilcoxon_two_sided_p": interaction_two_sided_w,
                "wilcoxon_one_sided_p_post_less_pre": interaction_one_sided_w,
                "signflip_two_sided_p": interaction_two_sided_sf,
                "signflip_one_sided_p_post_less_pre": interaction_p,
                "n_signflip_permutations": n_permutations,
                "wilcoxon_two_sided_holm_p": np.nan,
                "wilcoxon_one_sided_holm_p": np.nan,
                "signflip_two_sided_holm_p": np.nan,
                "signflip_one_sided_holm_p": np.nan,
            }
        ]
    )
    return pd.concat([tests, interaction_row], ignore_index=True)



def draw_box(
    ax: plt.Axes,
    values: np.ndarray,
    position: float,
    alpha: float,
) -> None:
    color = FIG3_POOLED_ML_PURPLE
    result = ax.boxplot(
        [values],
        positions=[position],
        widths=0.65,
        patch_artist=True,
        showfliers=False,
        manage_ticks=False,
    )
    for patch in result["boxes"]:
        patch.set_facecolor(color)
        patch.set_edgecolor(color)
        patch.set_alpha(alpha)
        patch.set_linewidth(1.4)
    for artist in result["whiskers"] + result["caps"]:
        artist.set_color("0.25")
        artist.set_linewidth(1.2)
    for artist in result["medians"]:
        artist.set_color("black")
        artist.set_linewidth(1.8)


def add_bracket(
    ax: plt.Axes,
    x1: float,
    x2: float,
    y: float,
    height: float,
    text: str,
) -> None:
    ax.plot(
        [x1, x1, x2, x2],
        [y, y + height, y + height, y],
        color="0.15",
        linewidth=1.1,
    )
    ax.text(
        (x1 + x2) / 2,
        y + height * 1.2,
        text,
        ha="center",
        va="bottom",
        fontsize=16,
    )


def plot_panel(
    by_bird: pd.DataFrame,
    tests: pd.DataFrame,
    output: Path,
    dpi: int,
    show: bool,
) -> None:
    positions = {
        "q75_pre": 0.0,
        "q75_post": 1.0,
        "below_pre": 3.1,
        "below_post": 4.1,
    }

    q75_pair_mask = (
        np.isfinite(by_bird["q75_pre_bc"].to_numpy(dtype=float))
        & np.isfinite(by_bird["q75_post_bc"].to_numpy(dtype=float))
    )
    below_pair_mask = (
        np.isfinite(by_bird["below_q75_pre_bc"].to_numpy(dtype=float))
        & np.isfinite(by_bird["below_q75_post_bc"].to_numpy(dtype=float))
    )

    arrays = {
        "q75_pre": by_bird.loc[q75_pair_mask, "q75_pre_bc"].to_numpy(dtype=float),
        "q75_post": by_bird.loc[q75_pair_mask, "q75_post_bc"].to_numpy(dtype=float),
        "below_pre": by_bird.loc[below_pair_mask, "below_q75_pre_bc"].to_numpy(dtype=float),
        "below_post": by_bird.loc[below_pair_mask, "below_q75_post_bc"].to_numpy(dtype=float),
    }

    fig, ax = plt.subplots(figsize=(8.3, 5.3))

    # Same Figure 3 pooled-M+L purple. Pre is lighter; Post more saturated.
    draw_box(ax, arrays["q75_pre"], positions["q75_pre"], alpha=0.28)
    draw_box(ax, arrays["q75_post"], positions["q75_post"], alpha=0.50)
    draw_box(ax, arrays["below_pre"], positions["below_pre"], alpha=0.28)
    draw_box(ax, arrays["below_post"], positions["below_post"], alpha=0.50)

    rng = np.random.default_rng(20260806)
    jitter_scale = 0.055

    for key, values in arrays.items():
        x = (
            np.full(len(values), positions[key])
            + rng.uniform(-jitter_scale, jitter_scale, len(values))
        )
        point_alpha = 0.82 if "pre" in key else 0.95
        ax.scatter(
            x,
            values,
            s=40,
            color=FIG3_POOLED_ML_PURPLE,
            alpha=point_alpha,
            edgecolors="white",
            linewidths=0.55,
            zorder=3,
        )

    ax.set_xticks(list(positions.values()))
    ax.set_xticklabels(["Pre", "Post", "Pre", "Post"], fontsize=16)
    ax.set_ylabel("Bhattacharyya coefficient", fontsize=19)

    # Manuscript-facing subset labels.
    trans = ax.get_xaxis_transform()
    ax.text(
        0.5,
        -0.16,
        "≥ Q75 ΔCV\nsyllables",
        ha="center",
        va="top",
        transform=trans,
        fontsize=15,
    )
    ax.text(
        3.6,
        -0.16,
        "< Q75 ΔCV\nsyllables",
        ha="center",
        va="top",
        transform=trans,
        fontsize=15,
    )

    all_values = np.concatenate(list(arrays.values()))
    data_min = float(np.nanmin(all_values))
    data_max = float(np.nanmax(all_values))
    data_span = max(data_max - data_min, 0.015)

    lower = max(0.0, data_min - 0.10 * data_span)
    bracket_base = data_max + 0.09 * data_span
    bracket_height = 0.035 * data_span

    q75_row = tests[
        tests["subset"] == ">= Q75 ΔCV syllables"
    ].iloc[0]
    below_row = tests[
        tests["subset"] == "< Q75 ΔCV syllables"
    ].iloc[0]

    # Preserve the original Figure 4D convention: display raw two-sided
    # paired Wilcoxon significance; adjusted/sign-flip values remain in CSV.
    q75_p = float(q75_row["wilcoxon_two_sided_p"])
    below_p = float(below_row["wilcoxon_two_sided_p"])

    add_bracket(
        ax,
        positions["q75_pre"],
        positions["q75_post"],
        bracket_base,
        bracket_height,
        p_label(q75_p),
    )
    add_bracket(
        ax,
        positions["below_pre"],
        positions["below_post"],
        bracket_base,
        bracket_height,
        p_label(below_p),
    )

    ax.set_ylim(lower, bracket_base + 0.17 * data_span)
    ax.set_xlim(-0.8, 4.9)
    ax.tick_params(axis="y", labelsize=14)
    ax.tick_params(axis="x", pad=8)

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.1)
    ax.spines["bottom"].set_linewidth(1.1)

    fig.subplots_adjust(
        left=0.15,
        right=0.98,
        top=0.96,
        bottom=0.31,
    )
    fig.savefig(
        output,
        dpi=dpi,
        bbox_inches="tight",
        pad_inches=0.08,
    )

    if show:
        plt.show()
    else:
        plt.close(fig)


def write_text_summary(
    path: Path,
    bc_path: str,
    selection_path: str,
    selection_column: str,
    by_bird: pd.DataFrame,
    tests: pd.DataFrame,
) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write(
            "Figure 4: Figure-3-defined Q75 ΔCV syllables vs below-Q75 syllables, "
            "Pre vs Post BC\n"
        )
        handle.write(
            "==========================================================================\n\n"
        )
        handle.write(f"BC input: {bc_path}\n")
        handle.write(f"Figure 3 quantile-selection input: {selection_path}\n")
        handle.write(f"Selection flag: {selection_column}\n")
        n_q75 = int(np.sum(
            np.isfinite(by_bird["q75_pre_bc"].to_numpy(float))
            & np.isfinite(by_bird["q75_post_bc"].to_numpy(float))
        ))
        n_below = int(np.sum(
            np.isfinite(by_bird["below_q75_pre_bc"].to_numpy(float))
            & np.isfinite(by_bird["below_q75_post_bc"].to_numpy(float))
        ))
        n_both = int(np.sum(
            np.isfinite(by_bird["q75_delta_bc"].to_numpy(float))
            & np.isfinite(by_bird["below_q75_delta_bc"].to_numpy(float))
        ))
        handle.write(f"Pooled M+L birds with >=Q75 BC: {n_q75}\n")
        handle.write(f"Pooled M+L birds with below-Q75 BC: {n_below}\n")
        handle.write(f"Pooled M+L birds with both subsets: {n_both}\n")
        handle.write(
            "Bird-level statistic: median BC across syllables within each "
            "subset and period\n"
        )
        handle.write(
            "Displayed tests: raw two-sided paired Wilcoxon, matching the "
            "original Figure 4D convention\n"
        )
        handle.write(
            "Additional one-sided, Holm-adjusted, exact sign-flip, and direct "
            "subset-contrast p values are reported in the tests CSV\n\n"
        )

        for subset in [
            ">= Q75 ΔCV syllables",
            "< Q75 ΔCV syllables",
        ]:
            row = tests[tests["subset"] == subset].iloc[0]
            handle.write(f"{subset}\n")
            handle.write("-" * len(subset) + "\n")
            handle.write(f"n birds: {int(row['n_birds'])}\n")
            handle.write(f"median Pre BC: {row['median_pre_bc']:.8g}\n")
            handle.write(f"median Post BC: {row['median_post_bc']:.8g}\n")
            handle.write(
                "median DeltaBC (Post - Pre): "
                f"{row['median_delta_bc_post_minus_pre']:.8g}\n"
            )
            handle.write(
                "two-sided Wilcoxon raw p: "
                f"{row['wilcoxon_two_sided_p']:.8g}\n"
            )
            handle.write(
                "two-sided Wilcoxon Holm p: "
                f"{row['wilcoxon_two_sided_holm_p']:.8g}\n"
            )
            handle.write(
                "one-sided Wilcoxon raw p (Post < Pre): "
                f"{row['wilcoxon_one_sided_p_post_less_pre']:.8g}\n"
            )
            handle.write(
                "one-sided exact sign-flip raw p (Post < Pre): "
                f"{row['signflip_one_sided_p_post_less_pre']:.8g}\n\n"
            )

        interaction = tests[
            tests["subset"] == "DeltaBC contrast"
        ].iloc[0]
        handle.write("Q75-vs-below-Q75 DeltaBC contrast\n")
        handle.write("---------------------------------\n")
        handle.write(
            "Mean [>=Q75 DeltaBC - below-Q75 DeltaBC]: "
            f"{interaction['mean_delta_bc_post_minus_pre']:.8g}\n"
        )
        handle.write(
            "One-sided exact sign-flip p (>=Q75 more negative): "
            f"{interaction['signflip_one_sided_p_post_less_pre']:.8g}\n"
        )
        handle.write(
            "One-sided paired Wilcoxon p (>=Q75 more negative): "
            f"{interaction['wilcoxon_one_sided_p_post_less_pre']:.8g}\n"
        )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Plot and test Pre vs Post BC in pooled medial+lateral birds for "
            "the exact Figure-3-defined >=Q75 ΔCV syllables and the Figure 3 "
            "qualifying syllables below Q75."
        )
    )

    parser.add_argument(
        "--bc-csv",
        required=True,
        help="BC metrics CSV containing Pre and Post BC values.",
    )
    parser.add_argument(
        "--quantile-selection-csv",
        required=True,
        help=(
            "Figure 3 syllable_level_quantile_selection.csv containing "
            "animal_id, syllable, and selected_Q75."
        ),
    )
    parser.add_argument(
        "--selection-column",
        default="selected_Q75",
        help="Boolean Figure 3 selection column. Default: selected_Q75",
    )
    parser.add_argument("--metadata-excel", default=None)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--show", action="store_true")
    args = parser.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    selection = read_quantile_selection(
        args.quantile_selection_csv,
        selection_column=args.selection_column,
    )

    # Use the full Figure 3 qualifying-pair set to identify the correct BC
    # syllable/cluster identifier column.
    all_fig3_pairs = selection[["animal_id", "syllable"]].drop_duplicates()

    bc, identifier_report = read_bc_table(
        args.bc_csv,
        args.metadata_excel,
        all_fig3_pairs,
    )

    identifier_report.to_csv(
        out_dir / "figure4_Q75_bc_identifier_column_match_report.csv",
        index=False,
    )

    # CRITICAL: inner merge keeps Figure 4 within the exact Figure 3
    # qualifying-syllable universe.
    merged = bc.merge(
        selection,
        on=["animal_id", "syllable"],
        how="inner",
    )
    merged["subset"] = np.where(
        merged["is_q75"],
        "q75_or_above",
        "below_q75",
    )

    merged.to_csv(
        out_dir / "figure4_Q75_prepost_bc_cluster_rows.csv",
        index=False,
    )

    # -----------------------------------------------------------------
    # Merge audit
    # -----------------------------------------------------------------
    fig3_total = (
        selection.groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_fig3_qualifying")
    )
    q75_requested = (
        selection.loc[selection["is_q75"]]
        .groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_q75_requested")
    )
    below_requested = (
        selection.loc[~selection["is_q75"]]
        .groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_below_q75_requested")
    )
    bc_matched_total = (
        merged.groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_fig3_pairs_with_bc")
    )
    q75_matched = (
        merged.loc[merged["is_q75"]]
        .groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_q75_with_bc")
    )
    below_matched = (
        merged.loc[~merged["is_q75"]]
        .groupby("animal_id")["syllable"]
        .nunique()
        .rename("n_below_q75_with_bc")
    )

    merge_audit = (
        pd.concat(
            [
                fig3_total,
                q75_requested,
                below_requested,
                bc_matched_total,
                q75_matched,
                below_matched,
            ],
            axis=1,
        )
        .fillna(0)
        .astype(
            {
                "n_fig3_qualifying": int,
                "n_q75_requested": int,
                "n_below_q75_requested": int,
                "n_fig3_pairs_with_bc": int,
                "n_q75_with_bc": int,
                "n_below_q75_with_bc": int,
            }
        )
        .reset_index()
    )

    merge_audit["n_q75_missing_bc"] = (
        merge_audit["n_q75_requested"] - merge_audit["n_q75_with_bc"]
    )
    merge_audit["n_below_q75_missing_bc"] = (
        merge_audit["n_below_q75_requested"]
        - merge_audit["n_below_q75_with_bc"]
    )

    merge_audit.to_csv(
        out_dir / "figure4_Q75_bc_token_merge_audit.csv",
        index=False,
    )

    print(
        f"[INFO] Matched {len(merged)} Figure 3 qualifying animal x syllable "
        f"pairs to BC data across {merged['animal_id'].nunique()} birds"
    )
    print(
        f"[INFO] Q75 BC rows: {int(merged['is_q75'].sum())}; "
        f"below-Q75 BC rows: {int((~merged['is_q75']).sum())}"
    )

    by_bird = make_bird_table(merged)
    by_bird.to_csv(
        out_dir / "figure4_Q75_prepost_bc_by_bird.csv",
        index=False,
    )

    tests = run_tests(by_bird)
    tests.to_csv(
        out_dir / "figure4_Q75_prepost_bc_tests.csv",
        index=False,
    )

    plot_path = (
        out_dir / "Figure4_Q75_prepost_BC_ML_Fig3colors.png"
    )
    plot_panel(
        by_bird,
        tests,
        plot_path,
        args.dpi,
        args.show,
    )

    summary_path = out_dir / "figure4_Q75_prepost_bc_summary.txt"
    write_text_summary(
        summary_path,
        args.bc_csv,
        args.quantile_selection_csv,
        args.selection_column,
        by_bird,
        tests,
    )

    print(f"[OK] Pooled M+L bird-level table contains: {len(by_bird)} birds")
    print(f"[OK] Wrote outputs to {out_dir}")
    for filename in [
        plot_path.name,
        "figure4_Q75_prepost_bc_cluster_rows.csv",
        "figure4_Q75_bc_identifier_column_match_report.csv",
        "figure4_Q75_prepost_bc_by_bird.csv",
        "figure4_Q75_bc_token_merge_audit.csv",
        "figure4_Q75_prepost_bc_tests.csv",
        summary_path.name,
    ]:
        print(" ", out_dir / filename)


if __name__ == "__main__":
    main()
