#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Create the top-15% Figure 3 phrase-duration panels as PNG files only.

This script makes three manuscript-style panels using one exact within-bird
upper-fraction selection:

1. Late-pre versus post phrase-duration SD scatterplot.
2. Bird-level change-in-CV boxplot.
3. Equal-bird, baseline-normalized CV rolling-median time course.

Selection
---------
Eligible syllables are ranked separately within each bird by the mean of their
late-pre and post phrase-duration variances (``--rank-on pooled`` by default).
The script retains exactly::

    ceil(top_fraction * number_of_eligible_syllables)

syllables per bird. The default ``--top-fraction 0.15`` therefore implements
the upper-15% operating point used in the exploratory analysis. Stable sorting
by syllable label resolves exact rank ties reproducibly.

Statistical unit
----------------
CV is estimated for each selected bird x syllable after equalizing late-pre and
post phrase counts. The script repeats this balancing 200 times by default and
averages the resulting metrics, matching the cutoff-scan analysis. Each bird is
then represented by the median delta-CV across its selected syllables. Exact
bird-label permutation tests compare pooled medial+lateral lesions with
lateral-only and sham groups. Holm correction is applied across the three
pairwise comparisons.

Expected inputs
---------------
--scatter-csv
    The balanced period-level table used for the existing Figure 3 scatter,
    usually ``usage_balanced_phrase_duration_stats.csv``. Required columns are
    detected from common names, including Animal ID, Syllable, Group,
    N_phrases, and Variance_ms2.

--duration-long-csv
    One row per phrase occurrence, with bird, syllable, duration, and either a
    relative-day column or recording date. A Late Pre/Post group column is
    optional because periods can be assigned from relative-day windows.

--metadata-excel
    Optional workbook containing bird IDs and lesion hit types. It is not needed
    when using the CSVs generated by generate_figure3_top15_inputs_from_json.py,
    because those files already contain lesion_group, lesion_surgery_date, and
    relative_day columns.

Example
-------
python figure3_top15_SDscatter_deltaCV_timecourse_pngonly.py \
  --scatter-csv "/Volumes/my_own_SSD/updated_AreaX_outputs/usage_balanced_phrase_duration_stats.csv" \
  --duration-long-csv "/Volumes/my_own_SSD/updated_AreaX_outputs/phrase_duration_batch_outputs/_batch_summary/all_birds_phrase_duration_long_latepre_post_epochs.csv" \
  --out-dir "/Volumes/my_own_SSD/updated_AreaX_outputs/Figure3_top15_CV" \
  --top-fraction 0.15 \
  --rank-on pooled \
  --pre-start-day -14 --pre-end-day -1 \
  --post-start-day 1 --post-end-day 14 \
  --x-min -30 --x-max 30 \
  --no-show

Outputs are PNG and CSV/TXT only; no PDF files are written.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import itertools
import json
import math
import warnings
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Optional, Sequence

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from matplotlib.ticker import FuncFormatter, LogLocator, NullFormatter
import numpy as np
import pandas as pd


# -----------------------------------------------------------------------------
# Canonical groups and Figure 3 palette
# -----------------------------------------------------------------------------
SHAM_GROUP = "sham saline injection"
LATERAL_GROUP = "Lateral lesion only"
COMPLETE_ML_GROUP = "Complete Medial and Lateral lesion"
PARTIAL_ML_GROUP = "Partial Medial and Lateral lesion"
POOLED_ML_GROUP = "Complete and partial medial and lateral lesion"
UNKNOWN_GROUP = "unknown"

DEFAULT_COLORS = {
    COMPLETE_ML_GROUP: "#3F007D",   # dark purple
    PARTIAL_ML_GROUP: "#7A4FB7",    # medium purple
    LATERAL_GROUP: "#A88BD9",       # light purple
    SHAM_GROUP: "#1B9E77",          # teal
    POOLED_ML_GROUP: "#7A4FB7",
    UNKNOWN_GROUP: "#4D4D4D",
}

SCATTER_ORDER = [
    COMPLETE_ML_GROUP,
    PARTIAL_ML_GROUP,
    LATERAL_GROUP,
    SHAM_GROUP,
]
BOX_ORDER = [SHAM_GROUP, LATERAL_GROUP, POOLED_ML_GROUP]
TIMECOURSE_ORDER = [POOLED_ML_GROUP, SHAM_GROUP]
LESION_DAY_COLOR = "#D62728"


# -----------------------------------------------------------------------------
# Small helpers
# -----------------------------------------------------------------------------
def standardize_text(value: Any) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    return " ".join(str(value).strip().split())


def normalized_text(value: Any) -> str:
    return standardize_text(value).lower().replace("_", " ").replace("-", " ")


def ensure_dir(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    return path


def stable_rng(seed: int, *parts: object) -> np.random.Generator:
    payload = "|".join([str(seed), *(str(part) for part in parts)]).encode("utf-8")
    digest = hashlib.sha256(payload).digest()
    derived = int.from_bytes(digest[:8], "little", signed=False)
    return np.random.default_rng(derived)


def first_existing_column(
    df: pd.DataFrame,
    requested: Optional[str],
    candidates: Sequence[str],
    label: str,
    *,
    required: bool = True,
) -> Optional[str]:
    if requested:
        if requested in df.columns:
            return requested
        raise ValueError(
            f"Requested {label} column {requested!r} was not found. "
            f"Available columns: {list(df.columns)}"
        )

    lookup = {
        "".join(ch.lower() for ch in str(col) if ch.isalnum()): col
        for col in df.columns
    }
    for candidate in candidates:
        key = "".join(ch.lower() for ch in candidate if ch.isalnum())
        if key in lookup:
            return lookup[key]
    if required:
        raise ValueError(
            f"Could not identify the {label} column. Available columns: {list(df.columns)}"
        )
    return None


def plain_number(x: float, pos: object = None) -> str:
    try:
        value = float(x)
    except Exception:
        return ""
    if not np.isfinite(value):
        return ""
    if abs(value) < 1e-12:
        return "0"
    magnitude = abs(value)
    if magnitude >= 10:
        text = f"{value:.0f}"
    elif magnitude >= 1:
        text = f"{value:.1f}"
    else:
        text = f"{value:.2f}"
    return text.rstrip("0").rstrip(".")


def pretty_axes(ax: plt.Axes, tick_size: float = 13.5) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_linewidth(1.0)
    ax.spines["bottom"].set_linewidth(1.0)
    ax.tick_params(axis="both", labelsize=tick_size, width=1.0, length=4)


def save_png(fig: plt.Figure, path: Path, dpi: int, show: bool) -> Path:
    if path.suffix.lower() != ".png":
        path = path.with_suffix(".png")
    fig.savefig(path, dpi=dpi, bbox_inches="tight", pad_inches=0.08)
    if show:
        plt.show()
    else:
        plt.close(fig)
    return path


def format_p(p: float) -> str:
    if not np.isfinite(p):
        return "NA"
    if p < 0.001:
        return "<0.001"
    return f"{p:.3f}"


def p_to_stars(p: float) -> str:
    if not np.isfinite(p):
        return "NA"
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    return "n.s."


def sample_sd(values: np.ndarray) -> float:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    return float(np.std(values, ddof=1)) if values.size >= 2 else np.nan


def safe_mean(values: Sequence[float]) -> float:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    return float(np.mean(arr)) if arr.size else np.nan


def safe_median(values: Sequence[float]) -> float:
    arr = np.asarray(values, dtype=float)
    arr = arr[np.isfinite(arr)]
    return float(np.median(arr)) if arr.size else np.nan


# -----------------------------------------------------------------------------
# Color configuration and lesion-group normalization
# -----------------------------------------------------------------------------
def normalize_hit_type(value: Any) -> str:
    text = normalized_text(value)
    compact = text.replace(" ", "")
    if not text:
        return UNKNOWN_GROUP
    if "sham" in text or ("saline" in text and "lesion" not in text):
        return SHAM_GROUP
    if "single hit" in text or "lateral only" in text or "lateral hit only" in text:
        return LATERAL_GROUP
    if "area x not visible" in text or "large lesion" in text or "largelesion" in compact:
        return COMPLETE_ML_GROUP
    if "complete" in text and "medial" in text and "lateral" in text:
        return COMPLETE_ML_GROUP
    if ("medial" in text and "lateral" in text) or "m+l" in compact or "combined" in text:
        return PARTIAL_ML_GROUP
    if compact in {"ml", "mediallateral", "medial+lateral", "medialandlateral"}:
        return PARTIAL_ML_GROUP
    return standardize_text(value) or UNKNOWN_GROUP


def pooled_group(value: Any) -> str:
    group = normalize_hit_type(value)
    if group in {COMPLETE_ML_GROUP, PARTIAL_ML_GROUP, POOLED_ML_GROUP}:
        return POOLED_ML_GROUP
    return group


def load_colors(path: Optional[Path]) -> dict[str, str]:
    colors = dict(DEFAULT_COLORS)
    if path is None:
        return colors
    with path.open("r", encoding="utf-8") as handle:
        cfg = json.load(handle)

    # Supports both the original Figure 3 {groups:{...}} format and the simpler
    # Figure 4 {colors:{...}} files supplied with this analysis.
    if isinstance(cfg.get("groups"), dict):
        for group, info in cfg["groups"].items():
            if isinstance(info, dict) and info.get("color"):
                canonical = normalize_hit_type(group)
                colors[canonical] = str(info["color"])
    if isinstance(cfg.get("colors"), dict):
        for group, color in cfg["colors"].items():
            canonical = normalize_hit_type(group)
            if canonical == PARTIAL_ML_GROUP and "medial" in normalized_text(group):
                colors[PARTIAL_ML_GROUP] = str(color)
                colors[POOLED_ML_GROUP] = str(color)
            else:
                colors[canonical] = str(color)
    return colors


# -----------------------------------------------------------------------------
# Metadata
# -----------------------------------------------------------------------------
def load_metadata(
    path: Optional[Path],
    *,
    preferred_sheet: Optional[str],
    animal_col_requested: Optional[str],
    hit_col_requested: Optional[str],
    date_col_requested: Optional[str],
) -> tuple[dict[str, str], dict[str, pd.Timestamp]]:
    if path is None:
        return {}, {}
    if not path.exists():
        raise FileNotFoundError(path)

    xls = pd.ExcelFile(path)
    sheets = list(xls.sheet_names)
    if preferred_sheet and preferred_sheet in sheets:
        sheets = [preferred_sheet] + [sheet for sheet in sheets if sheet != preferred_sheet]

    hit_map: dict[str, str] = {}
    date_map: dict[str, pd.Timestamp] = {}
    for sheet in sheets:
        df = pd.read_excel(path, sheet_name=sheet)
        animal_col = first_existing_column(
            df,
            animal_col_requested if animal_col_requested in df.columns else None,
            ["Animal ID", "animal_id", "bird", "Bird ID"],
            "metadata animal",
            required=False,
        )
        if animal_col is None:
            continue

        if not hit_map:
            hit_col = first_existing_column(
                df,
                hit_col_requested if hit_col_requested in df.columns else None,
                ["Lesion hit type", "Hit type", "Hit Type", "lesion_group", "Treatment type"],
                "metadata lesion hit type",
                required=False,
            )
            if hit_col:
                for _, row in df[[animal_col, hit_col]].dropna(subset=[animal_col]).iterrows():
                    bird = standardize_text(row[animal_col])
                    if bird:
                        hit_map[bird] = normalize_hit_type(row[hit_col])

        if not date_map:
            date_col = first_existing_column(
                df,
                date_col_requested if date_col_requested in df.columns else None,
                ["Treatment date", "Lesion date", "Surgery date", "treatment_date", "lesion_surgery_date"],
                "metadata treatment date",
                required=False,
            )
            if date_col:
                temp = df[[animal_col, date_col]].copy()
                temp[date_col] = pd.to_datetime(temp[date_col], errors="coerce")
                for _, row in temp.dropna(subset=[animal_col, date_col]).iterrows():
                    bird = standardize_text(row[animal_col])
                    if bird:
                        date_map[bird] = pd.Timestamp(row[date_col]).normalize()

        if hit_map and date_map:
            break

    return hit_map, date_map


# -----------------------------------------------------------------------------
# Exact upper-fraction selection and SD scatter table
# -----------------------------------------------------------------------------
def prepare_selected_scatter(
    path: Path,
    *,
    hit_map: Mapping[str, str],
    top_fraction: float,
    rank_on: str,
    pre_group: str,
    post_group: str,
    min_n_phrases: int,
    animal_col_requested: Optional[str],
    syllable_col_requested: Optional[str],
    group_col_requested: Optional[str],
    variance_col_requested: Optional[str],
    n_col_requested: Optional[str],
) -> tuple[pd.DataFrame, pd.DataFrame]:
    df = pd.read_csv(path)
    animal_col = first_existing_column(
        df, animal_col_requested, ["Animal ID", "animal_id", "bird", "Bird ID"], "scatter animal"
    )
    syllable_col = first_existing_column(
        df, syllable_col_requested, ["Syllable", "syllable", "label", "syllable_label"], "scatter syllable"
    )
    group_col = first_existing_column(
        df, group_col_requested, ["Group", "group", "epoch", "Period"], "scatter period"
    )
    variance_col = first_existing_column(
        df,
        variance_col_requested,
        ["Variance_ms2", "Variance (ms^2)", "variance_ms2", "variance"],
        "scatter variance",
    )
    n_col = first_existing_column(
        df,
        n_col_requested,
        ["N_phrases", "n_phrases", "N", "count", "n"],
        "scatter phrase count",
        required=False,
    )
    embedded_group_col = first_existing_column(
        df,
        None,
        ["lesion_group", "display_group", "Lesion hit type", "Hit type", "Treatment type"],
        "embedded scatter lesion group",
        required=False,
    )
    effective_hit_map = dict(hit_map)
    if embedded_group_col is not None:
        embedded = (
            df[[animal_col, embedded_group_col]]
            .dropna(subset=[animal_col, embedded_group_col])
            .drop_duplicates(subset=[animal_col])
        )
        for _, row in embedded.iterrows():
            bird = standardize_text(row[animal_col])
            if bird and bird not in effective_hit_map:
                effective_hit_map[bird] = normalize_hit_type(row[embedded_group_col])

    work = df[df[group_col].astype(str).isin([pre_group, post_group])].copy()
    work[variance_col] = pd.to_numeric(work[variance_col], errors="coerce")
    if n_col:
        work[n_col] = pd.to_numeric(work[n_col], errors="coerce")
        work = work[work[n_col].fillna(0) >= min_n_phrases]

    long = (
        work.groupby([animal_col, syllable_col, group_col], dropna=False)[variance_col]
        .mean()
        .reset_index()
    )
    wide = long.pivot_table(
        index=[animal_col, syllable_col], columns=group_col, values=variance_col, aggfunc="mean"
    ).reset_index()
    if pre_group not in wide.columns or post_group not in wide.columns:
        raise ValueError(f"Could not find both {pre_group!r} and {post_group!r} after pivoting {path}.")

    wide = wide.rename(
        columns={animal_col: "animal_id", syllable_col: "syllable", pre_group: "pre_variance", post_group: "post_variance"}
    )
    wide["animal_id"] = wide["animal_id"].astype(str)
    wide["syllable"] = wide["syllable"].astype(str)
    wide["pre_variance"] = pd.to_numeric(wide["pre_variance"], errors="coerce")
    wide["post_variance"] = pd.to_numeric(wide["post_variance"], errors="coerce")
    wide = wide.dropna(subset=["pre_variance", "post_variance"])
    wide = wide[(wide["pre_variance"] > 0) & (wide["post_variance"] > 0)].copy()

    rank_on = rank_on.lower()
    if rank_on == "pre":
        wide["rank_metric"] = wide["pre_variance"]
    elif rank_on == "post":
        wide["rank_metric"] = wide["post_variance"]
    elif rank_on == "max":
        wide["rank_metric"] = wide[["pre_variance", "post_variance"]].max(axis=1)
    elif rank_on in {"pooled", "mean", "pooled_mean"}:
        wide["rank_metric"] = wide[["pre_variance", "post_variance"]].mean(axis=1)
    else:
        raise ValueError("--rank-on must be pre, post, max, or pooled")

    selected_parts: list[pd.DataFrame] = []
    audit_rows: list[dict[str, Any]] = []
    for bird, bird_df in wide.groupby("animal_id", sort=True):
        ordered = bird_df.sort_values(
            ["rank_metric", "syllable"], ascending=[False, True], kind="mergesort"
        ).copy()
        n_eligible = len(ordered)
        n_selected = max(1, int(math.ceil(top_fraction * n_eligible)))
        selected = ordered.head(n_selected).copy()
        selected["selection_rank"] = np.arange(1, len(selected) + 1)
        selected["n_eligible_syllables"] = n_eligible
        selected["n_selected_syllables"] = n_selected
        selected["realized_fraction"] = n_selected / n_eligible
        selected_parts.append(selected)
        audit_rows.append(
            {
                "animal_id": bird,
                "n_eligible_syllables": n_eligible,
                "n_selected_syllables": n_selected,
                "target_fraction": top_fraction,
                "realized_fraction": n_selected / n_eligible,
                "selected_syllables": ";".join(selected["syllable"].tolist()),
            }
        )

    selected = pd.concat(selected_parts, ignore_index=True) if selected_parts else wide.iloc[0:0].copy()
    selected["pre_sd_s"] = np.sqrt(selected["pre_variance"]) / 1000.0
    selected["post_sd_s"] = np.sqrt(selected["post_variance"]) / 1000.0
    selected["display_group"] = selected["animal_id"].map(effective_hit_map).fillna(UNKNOWN_GROUP).map(normalize_hit_type)
    audit = pd.DataFrame(audit_rows)
    if not audit.empty:
        audit["display_group"] = audit["animal_id"].map(effective_hit_map).fillna(UNKNOWN_GROUP).map(normalize_hit_type)
    return selected.reset_index(drop=True), audit


def plot_sd_scatter(
    df: pd.DataFrame,
    path: Path,
    *,
    colors: Mapping[str, str],
    dpi: int,
    show: bool,
) -> Path:
    finite = df.replace([np.inf, -np.inf], np.nan).dropna(subset=["pre_sd_s", "post_sd_s"])
    finite = finite[(finite["pre_sd_s"] > 0) & (finite["post_sd_s"] > 0)].copy()
    if finite.empty:
        raise ValueError("No positive SD values were available for the scatterplot.")

    all_values = np.concatenate([finite["pre_sd_s"].to_numpy(), finite["post_sd_s"].to_numpy()])
    log_values = np.log10(all_values)
    span = max(float(log_values.max() - log_values.min()), 1e-6)
    lower = float(10 ** (log_values.min() - 0.045 * span))
    upper = float(10 ** (log_values.max() + 0.045 * span))

    fig, ax = plt.subplots(figsize=(7.2, 6.2))
    ax.plot([lower, upper], [lower, upper], linestyle="--", linewidth=1.6, color="red", alpha=0.80, zorder=0)
    for group in reversed(SCATTER_ORDER):
        group_df = finite[finite["display_group"] == group]
        if group_df.empty:
            continue
        ax.scatter(
            group_df["pre_sd_s"],
            group_df["post_sd_s"],
            s=30,
            color=colors.get(group, DEFAULT_COLORS[UNKNOWN_GROUP]),
            alpha=0.78,
            edgecolors="none",
            zorder=2,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(lower, upper)
    ax.set_ylim(lower, upper)
    ax.set_xlabel("Late pre-lesion phrase-duration SD (s)", fontsize=18)
    ax.set_ylabel("Post-lesion phrase-duration SD (s)", fontsize=18)
    pretty_axes(ax, tick_size=14)
    formatter = FuncFormatter(plain_number)
    locator = LogLocator(base=10.0, subs=(1.0, 2.0, 5.0))
    ax.xaxis.set_major_locator(locator)
    ax.yaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)
    ax.yaxis.set_major_formatter(formatter)
    ax.xaxis.set_minor_formatter(NullFormatter())
    ax.yaxis.set_minor_formatter(NullFormatter())
    fig.subplots_adjust(left=0.16, right=0.98, bottom=0.15, top=0.98)
    return save_png(fig, path, dpi, show)


def save_scatter_legend(path: Path, colors: Mapping[str, str], dpi: int) -> Path:
    labels = {
        COMPLETE_ML_GROUP: "Complete Medial and Lateral lesion",
        PARTIAL_ML_GROUP: "Partial Medial and Lateral lesion",
        LATERAL_GROUP: "Lateral lesion only",
        SHAM_GROUP: "sham saline injection",
    }
    handles = [
        Line2D(
            [0], [0], marker="o", linestyle="None", markersize=8,
            markerfacecolor=colors[group], markeredgecolor="none", label=labels[group]
        )
        for group in SCATTER_ORDER
    ]
    fig, ax = plt.subplots(figsize=(5.7, 1.55))
    ax.axis("off")
    ax.legend(handles=handles, frameon=False, fontsize=12.5, loc="center", ncol=1)
    return save_png(fig, path, dpi, False)


# -----------------------------------------------------------------------------
# Phrase-occurrence long table and balanced CV metrics
# -----------------------------------------------------------------------------
def prepare_long_table(
    path: Path,
    *,
    hit_map: Mapping[str, str],
    treatment_dates: Mapping[str, pd.Timestamp],
    duration_unit: str,
    animal_col_requested: Optional[str],
    syllable_col_requested: Optional[str],
    duration_col_requested: Optional[str],
    day_col_requested: Optional[str],
    date_col_requested: Optional[str],
    period_col_requested: Optional[str],
) -> pd.DataFrame:
    df = pd.read_csv(path)
    animal_col = first_existing_column(
        df, animal_col_requested, ["animal_id", "Animal ID", "bird", "Bird ID"], "long animal"
    )
    syllable_col = first_existing_column(
        df, syllable_col_requested, ["syllable", "Syllable", "label", "syllable_label"], "long syllable"
    )
    duration_col = first_existing_column(
        df,
        duration_col_requested,
        ["Phrase Duration (ms)", "phrase_duration_ms", "duration_ms", "Phrase Duration (s)", "phrase_duration_s", "duration_s", "duration"],
        "phrase duration",
    )
    day_col = first_existing_column(
        df,
        day_col_requested,
        ["relative_day", "Days relative to lesion", "day_relative_to_lesion", "relative day"],
        "relative day",
        required=False,
    )
    date_col = first_existing_column(
        df,
        date_col_requested,
        ["Date", "date", "recording_date", "Recording date", "creation_date"],
        "recording date",
        required=False,
    )
    period_col = first_existing_column(
        df,
        period_col_requested,
        ["Group", "group", "epoch", "Period", "period"],
        "period",
        required=False,
    )
    embedded_group_col = first_existing_column(
        df,
        None,
        ["lesion_group", "display_group", "Lesion hit type", "Hit type", "Treatment type"],
        "embedded long-table lesion group",
        required=False,
    )
    embedded_surgery_col = first_existing_column(
        df,
        None,
        ["lesion_surgery_date", "Treatment date", "Lesion date", "Surgery date", "treatment_date"],
        "embedded surgery date",
        required=False,
    )

    work = df.rename(
        columns={animal_col: "animal_id", syllable_col: "syllable", duration_col: "duration_raw"}
    ).copy()
    work["animal_id"] = work["animal_id"].astype(str)
    work["syllable"] = work["syllable"].astype(str)
    work["duration_s"] = pd.to_numeric(work["duration_raw"], errors="coerce")

    requested_unit = duration_unit.lower()
    if requested_unit == "auto":
        requested_unit = "ms" if "ms" in duration_col.lower() else "s"
    if requested_unit == "ms":
        work["duration_s"] = work["duration_s"] / 1000.0
    elif requested_unit != "s":
        raise ValueError("--duration-unit must be auto, ms, or s")

    if day_col:
        work["relative_day"] = pd.to_numeric(work[day_col], errors="coerce")
    elif date_col:
        work["recording_date"] = pd.to_datetime(work[date_col], errors="coerce").dt.normalize()
        work["treatment_date"] = work["animal_id"].map(treatment_dates)
        if embedded_surgery_col is not None:
            embedded_dates = pd.to_datetime(df[embedded_surgery_col], errors="coerce").dt.normalize()
            work["treatment_date"] = work["treatment_date"].fillna(embedded_dates)
        work["relative_day"] = (work["recording_date"] - work["treatment_date"]).dt.days
    else:
        work["relative_day"] = np.nan

    if period_col:
        work["period_raw"] = work[period_col].astype(str)
    else:
        work["period_raw"] = ""

    mapped_group = work["animal_id"].map(hit_map)
    if embedded_group_col is not None:
        mapped_group = mapped_group.fillna(df[embedded_group_col])
    work["display_group"] = mapped_group.fillna(UNKNOWN_GROUP).map(normalize_hit_type)
    work = work[np.isfinite(work["duration_s"]) & (work["duration_s"] > 0)].copy()
    return work.reset_index(drop=True)


def assign_analysis_periods(
    df: pd.DataFrame,
    *,
    pre_group: str,
    post_group: str,
    pre_start_day: int,
    pre_end_day: int,
    post_start_day: int,
    post_end_day: int,
) -> pd.DataFrame:
    work = df.copy()
    period_norm = work["period_raw"].map(normalized_text)
    pre_norm = normalized_text(pre_group)
    post_norm = normalized_text(post_group)
    work["analysis_period"] = ""
    work.loc[period_norm == pre_norm, "analysis_period"] = "Late Pre"
    work.loc[period_norm == post_norm, "analysis_period"] = "Post"

    day = pd.to_numeric(work["relative_day"], errors="coerce")
    unset = work["analysis_period"].eq("")
    work.loc[unset & day.between(pre_start_day, pre_end_day), "analysis_period"] = "Late Pre"
    work.loc[unset & day.between(post_start_day, post_end_day), "analysis_period"] = "Post"
    return work


@dataclass
class BalancedMetrics:
    n_pre: int
    n_post: int
    n_balance: int
    n_pre_days: int
    n_post_days: int
    pre_mean_s: float
    post_mean_s: float
    pre_sd_s: float
    post_sd_s: float
    pre_cv: float
    post_cv: float
    delta_cv: float


def balanced_cv_metrics(
    pre: np.ndarray,
    post: np.ndarray,
    pre_days: np.ndarray,
    post_days: np.ndarray,
    *,
    min_phrases: int,
    min_days: int,
    draws: int,
    rng: np.random.Generator,
) -> Optional[BalancedMetrics]:
    pre = np.asarray(pre, dtype=float)
    post = np.asarray(post, dtype=float)
    pre = pre[np.isfinite(pre) & (pre > 0)]
    post = post[np.isfinite(post) & (post > 0)]
    n_pre_days = int(pd.Series(pre_days).dropna().nunique())
    n_post_days = int(pd.Series(post_days).dropna().nunique())
    if len(pre) < min_phrases or len(post) < min_phrases:
        return None
    if min_days > 0 and (n_pre_days < min_days or n_post_days < min_days):
        return None
    n_balance = min(len(pre), len(post))
    if n_balance < 2:
        return None

    values: dict[str, list[float]] = {
        "pre_mean": [], "post_mean": [], "pre_sd": [], "post_sd": [],
        "pre_cv": [], "post_cv": [], "delta_cv": [],
    }
    for _ in range(draws):
        pre_draw = pre if len(pre) == n_balance else pre[rng.choice(len(pre), size=n_balance, replace=False)]
        post_draw = post if len(post) == n_balance else post[rng.choice(len(post), size=n_balance, replace=False)]
        pre_mean = float(np.mean(pre_draw))
        post_mean = float(np.mean(post_draw))
        pre_sd = sample_sd(pre_draw)
        post_sd = sample_sd(post_draw)
        if not all(np.isfinite(x) for x in [pre_mean, post_mean, pre_sd, post_sd]):
            continue
        if pre_mean <= 0 or post_mean <= 0:
            continue
        pre_cv = pre_sd / pre_mean
        post_cv = post_sd / post_mean
        delta_cv = post_cv - pre_cv
        for key, value in [
            ("pre_mean", pre_mean), ("post_mean", post_mean),
            ("pre_sd", pre_sd), ("post_sd", post_sd),
            ("pre_cv", pre_cv), ("post_cv", post_cv), ("delta_cv", delta_cv),
        ]:
            values[key].append(value)

    if not values["delta_cv"]:
        return None
    return BalancedMetrics(
        n_pre=len(pre), n_post=len(post), n_balance=n_balance,
        n_pre_days=n_pre_days, n_post_days=n_post_days,
        pre_mean_s=safe_mean(values["pre_mean"]), post_mean_s=safe_mean(values["post_mean"]),
        pre_sd_s=safe_mean(values["pre_sd"]), post_sd_s=safe_mean(values["post_sd"]),
        pre_cv=safe_mean(values["pre_cv"]), post_cv=safe_mean(values["post_cv"]),
        delta_cv=safe_mean(values["delta_cv"]),
    )


def calculate_selected_cv_metrics(
    long_df: pd.DataFrame,
    selected_pairs: pd.DataFrame,
    *,
    min_period_phrases: int,
    min_period_days: int,
    balance_draws: int,
    seed: int,
) -> pd.DataFrame:
    selected = selected_pairs[["animal_id", "syllable", "selection_rank", "n_eligible_syllables", "n_selected_syllables", "realized_fraction"]].copy()
    selected["animal_id"] = selected["animal_id"].astype(str)
    selected["syllable"] = selected["syllable"].astype(str)
    work = long_df.merge(selected, on=["animal_id", "syllable"], how="inner")

    rows: list[dict[str, Any]] = []
    for (bird, syllable), group in work.groupby(["animal_id", "syllable"], sort=True):
        pre = group[group["analysis_period"] == "Late Pre"]
        post = group[group["analysis_period"] == "Post"]
        metrics = balanced_cv_metrics(
            pre["duration_s"].to_numpy(), post["duration_s"].to_numpy(),
            pre["relative_day"].to_numpy(), post["relative_day"].to_numpy(),
            min_phrases=min_period_phrases,
            min_days=min_period_days,
            draws=balance_draws,
            rng=stable_rng(seed, "period_balance", bird, syllable),
        )
        if metrics is None:
            continue
        first = group.iloc[0]
        rows.append(
            {
                "animal_id": bird,
                "syllable": syllable,
                "display_group": normalize_hit_type(first["display_group"]),
                "pooled_group": pooled_group(first["display_group"]),
                "selection_rank": int(first["selection_rank"]),
                "n_eligible_syllables": int(first["n_eligible_syllables"]),
                "n_selected_syllables": int(first["n_selected_syllables"]),
                "realized_fraction": float(first["realized_fraction"]),
                **metrics.__dict__,
            }
        )
    return pd.DataFrame(rows)


def bird_level_cv_table(syllable_metrics: pd.DataFrame) -> pd.DataFrame:
    if syllable_metrics.empty:
        return pd.DataFrame()
    rows = []
    for bird, group in syllable_metrics.groupby("animal_id", sort=True):
        first = group.iloc[0]
        rows.append(
            {
                "animal_id": bird,
                "display_group": first["display_group"],
                "pooled_group": first["pooled_group"],
                "n_selected_with_cv": int(group["syllable"].nunique()),
                "pre_cv": float(group["pre_cv"].median()),
                "post_cv": float(group["post_cv"].median()),
                "delta_cv": float(group["delta_cv"].median()),
            }
        )
    return pd.DataFrame(rows)


# -----------------------------------------------------------------------------
# Exact bird-label permutation tests
# -----------------------------------------------------------------------------
def exact_permutation_p(
    x: np.ndarray,
    y: np.ndarray,
    *,
    alternative: str,
    max_exact: int,
    monte_carlo_reps: int,
    rng: np.random.Generator,
) -> tuple[float, str, int]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    x = x[np.isfinite(x)]
    y = y[np.isfinite(y)]
    if len(x) == 0 or len(y) == 0:
        return np.nan, "none", 0
    observed = float(np.mean(x) - np.mean(y))
    pooled = np.concatenate([x, y])
    nx = len(x)
    total = math.comb(len(pooled), nx)

    def extreme(stat: float) -> bool:
        if alternative == "greater":
            return stat >= observed - 1e-15
        if alternative == "less":
            return stat <= observed + 1e-15
        return abs(stat) >= abs(observed) - 1e-15

    if total <= max_exact:
        count = 0
        for indices in itertools.combinations(range(len(pooled)), nx):
            mask = np.zeros(len(pooled), dtype=bool)
            mask[list(indices)] = True
            stat = float(np.mean(pooled[mask]) - np.mean(pooled[~mask]))
            count += int(extreme(stat))
        return count / total, "exact", total

    count = 0
    for _ in range(monte_carlo_reps):
        perm = rng.permutation(pooled)
        stat = float(np.mean(perm[:nx]) - np.mean(perm[nx:]))
        count += int(extreme(stat))
    return (count + 1) / (monte_carlo_reps + 1), "monte_carlo", monte_carlo_reps


def bootstrap_mean_difference_ci(
    x: np.ndarray,
    y: np.ndarray,
    *,
    reps: int,
    rng: np.random.Generator,
) -> tuple[float, float]:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    x = x[np.isfinite(x)]
    y = y[np.isfinite(y)]
    if not len(x) or not len(y) or reps < 1:
        return np.nan, np.nan
    boot = np.empty(reps, dtype=float)
    for index in range(reps):
        xb = rng.choice(x, size=len(x), replace=True)
        yb = rng.choice(y, size=len(y), replace=True)
        boot[index] = np.mean(xb) - np.mean(yb)
    low, high = np.percentile(boot, [2.5, 97.5])
    return float(low), float(high)


def holm_adjust(p_values: Sequence[float]) -> np.ndarray:
    p = np.asarray(p_values, dtype=float)
    adjusted = np.full_like(p, np.nan)
    finite_idx = np.where(np.isfinite(p))[0]
    if not len(finite_idx):
        return adjusted
    order = finite_idx[np.argsort(p[finite_idx])]
    running = 0.0
    m = len(order)
    for rank, idx in enumerate(order):
        value = min(1.0, (m - rank) * p[idx])
        running = max(running, value)
        adjusted[idx] = running
    return adjusted


def run_pairwise_tests(
    bird_df: pd.DataFrame,
    *,
    seed: int,
    bootstrap_reps: int,
    max_exact: int,
    monte_carlo_reps: int,
) -> pd.DataFrame:
    comparisons = [
        (POOLED_ML_GROUP, LATERAL_GROUP),
        (POOLED_ML_GROUP, SHAM_GROUP),
        (LATERAL_GROUP, SHAM_GROUP),
    ]
    rows: list[dict[str, Any]] = []
    for group1, group2 in comparisons:
        x = bird_df.loc[bird_df["pooled_group"] == group1, "delta_cv"].to_numpy(dtype=float)
        y = bird_df.loc[bird_df["pooled_group"] == group2, "delta_cv"].to_numpy(dtype=float)
        p_greater, method, n_perm = exact_permutation_p(
            x, y, alternative="greater", max_exact=max_exact,
            monte_carlo_reps=monte_carlo_reps,
            rng=stable_rng(seed, "perm", group1, group2),
        )
        p_two, _, _ = exact_permutation_p(
            x, y, alternative="two-sided", max_exact=max_exact,
            monte_carlo_reps=monte_carlo_reps,
            rng=stable_rng(seed, "perm_two", group1, group2),
        )
        ci_low, ci_high = bootstrap_mean_difference_ci(
            x, y, reps=bootstrap_reps,
            rng=stable_rng(seed, "bootstrap", group1, group2),
        )
        rows.append(
            {
                "comparison": f"{group1}_vs_{group2}",
                "group1": group1,
                "group2": group2,
                "n_group1": len(x),
                "n_group2": len(y),
                "group1_mean_delta_cv": safe_mean(x),
                "group1_median_delta_cv": safe_median(x),
                "group2_mean_delta_cv": safe_mean(y),
                "group2_median_delta_cv": safe_median(y),
                "mean_difference_group1_minus_group2": safe_mean(x) - safe_mean(y),
                "bootstrap_ci_low": ci_low,
                "bootstrap_ci_high": ci_high,
                "alternative": "group1 > group2",
                "p_one_sided": p_greater,
                "p_two_sided": p_two,
                "permutation_method": method,
                "n_permutations": n_perm,
            }
        )
    result = pd.DataFrame(rows)
    if not result.empty:
        result["p_one_sided_holm"] = holm_adjust(result["p_one_sided"].to_numpy())
        result["p_two_sided_holm"] = holm_adjust(result["p_two_sided"].to_numpy())
    return result


def plot_delta_cv_boxplot(
    bird_df: pd.DataFrame,
    stats_df: pd.DataFrame,
    path: Path,
    *,
    colors: Mapping[str, str],
    annotation_style: str,
    dpi: int,
    show: bool,
) -> Path:
    work = bird_df[bird_df["pooled_group"].isin(BOX_ORDER)].copy()
    fig, ax = plt.subplots(figsize=(6.7, 5.0))
    rng = np.random.default_rng(0)
    positions = {group: idx for idx, group in enumerate(BOX_ORDER)}

    all_values: list[float] = []
    for group in BOX_ORDER:
        values = work.loc[work["pooled_group"] == group, "delta_cv"].dropna().to_numpy(dtype=float)
        if not len(values):
            continue
        all_values.extend(values.tolist())
        position = positions[group]
        color = colors.get(group, DEFAULT_COLORS[UNKNOWN_GROUP])
        box = ax.boxplot([values], positions=[position], widths=0.55, patch_artist=True, showfliers=False)
        for patch in box["boxes"]:
            patch.set_facecolor(color)
            patch.set_edgecolor(color)
            patch.set_alpha(0.35)
            patch.set_linewidth(1.5)
        for item in box["whiskers"] + box["caps"]:
            item.set_color(color)
            item.set_linewidth(1.4)
        for median in box["medians"]:
            median.set_color("0.25")
            median.set_linewidth(1.6)
        jitter = rng.uniform(-0.07, 0.07, size=len(values))
        ax.scatter(
            np.full(len(values), position) + jitter, values,
            s=34, color=color, alpha=0.90, edgecolors="none", zorder=3,
        )

    ax.axhline(0, color="0.45", linestyle="--", linewidth=1.0, zorder=0)
    ax.set_xticks(range(len(BOX_ORDER)))
    ax.set_xticklabels([
        "sham saline\ninjection",
        "Lateral lesion\nonly",
        "Complete and partial\nmedial and lateral lesion",
    ], fontsize=12.5)
    ax.set_ylabel("Δ coefficient of variation", fontsize=17)
    pretty_axes(ax, tick_size=13)
    ax.yaxis.set_major_formatter(FuncFormatter(plain_number))

    if all_values:
        y_min = min(min(all_values), 0)
        y_max = max(max(all_values), 0)
        span = max(y_max - y_min, 0.10)
        bracket_base = y_max + 0.08 * span
        bracket_gap = 0.13 * span

        # Display the two anatomically central comparisons; all three are in CSV.
        bracket_specs = [
            (LATERAL_GROUP, POOLED_ML_GROUP, bracket_base),
            (SHAM_GROUP, POOLED_ML_GROUP, bracket_base + bracket_gap),
        ]
        for group1, group2, height in bracket_specs:
            row = stats_df[
                ((stats_df["group1"] == group2) & (stats_df["group2"] == group1))
                | ((stats_df["group1"] == group1) & (stats_df["group2"] == group2))
            ]
            if row.empty:
                continue
            p = float(row.iloc[0]["p_one_sided_holm"])
            label = p_to_stars(p) if annotation_style == "stars" else f"p={format_p(p)}"
            x1, x2 = positions[group1], positions[group2]
            tick = 0.025 * span
            ax.plot([x1, x1, x2, x2], [height, height + tick, height + tick, height], color="0.15", linewidth=1.0)
            ax.text((x1 + x2) / 2, height + tick + 0.012 * span, label, ha="center", va="bottom", fontsize=11.5)
        ax.set_ylim(y_min - 0.08 * span, bracket_base + bracket_gap + 0.18 * span)

    fig.subplots_adjust(left=0.17, right=0.98, bottom=0.22, top=0.98)
    return save_png(fig, path, dpi, show)


# -----------------------------------------------------------------------------
# Daily CV and equal-bird rolling time course
# -----------------------------------------------------------------------------
def calculate_daily_cv(
    long_df: pd.DataFrame,
    selected_pairs: pd.DataFrame,
    *,
    min_daily_phrases: int,
    x_min: int,
    x_max: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    selected = selected_pairs[["animal_id", "syllable"]].drop_duplicates().copy()
    selected["animal_id"] = selected["animal_id"].astype(str)
    selected["syllable"] = selected["syllable"].astype(str)
    work = long_df.merge(selected, on=["animal_id", "syllable"], how="inner")
    work["relative_day"] = pd.to_numeric(work["relative_day"], errors="coerce")
    work = work[np.isfinite(work["relative_day"])]
    work = work[work["relative_day"].between(x_min, x_max)].copy()
    if work.empty:
        raise ValueError(
            "No selected phrase occurrences had a usable relative day. Provide a relative-day "
            "column, or a recording date plus treatment dates in the metadata workbook."
        )

    per_syllable = (
        work.groupby(["animal_id", "syllable", "display_group", "relative_day"], dropna=False)["duration_s"]
        .agg(n_phrases="size", mean_s="mean", sd_s="std")
        .reset_index()
    )
    per_syllable = per_syllable[per_syllable["n_phrases"] >= min_daily_phrases].copy()
    per_syllable["cv"] = per_syllable["sd_s"] / per_syllable["mean_s"]
    per_syllable.loc[~np.isfinite(per_syllable["cv"]) | (per_syllable["mean_s"] <= 0), "cv"] = np.nan
    per_syllable["pooled_group"] = per_syllable["display_group"].map(pooled_group)

    bird_daily = (
        per_syllable.groupby(["animal_id", "pooled_group", "relative_day"], dropna=False)
        .agg(
            cv=("cv", "median"),
            n_selected_syllables=("syllable", "nunique"),
            total_phrases=("n_phrases", "sum"),
        )
        .reset_index()
    )
    return per_syllable, bird_daily


def normalize_to_late_pre(
    bird_daily: pd.DataFrame,
    *,
    baseline_start: int,
    baseline_end: int,
    min_baseline_days: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    baseline_rows = []
    for bird, group in bird_daily.groupby("animal_id", sort=True):
        baseline = group[group["relative_day"].between(baseline_start, baseline_end)]["cv"].dropna().to_numpy()
        if len(baseline) < min_baseline_days:
            warnings.warn(
                f"Skipping {bird} from the normalized time course: {len(baseline)} usable baseline days; "
                f"need {min_baseline_days}."
            )
            continue
        baseline_rows.append(
            {
                "animal_id": bird,
                "baseline_start_day": baseline_start,
                "baseline_end_day": baseline_end,
                "n_baseline_days": len(baseline),
                "baseline_cv_median": float(np.median(baseline)),
                "baseline_cv_q25": float(np.percentile(baseline, 25)),
                "baseline_cv_q75": float(np.percentile(baseline, 75)),
            }
        )
    baseline_df = pd.DataFrame(baseline_rows)
    if baseline_df.empty:
        raise ValueError("No birds had enough late-pre baseline days for the CV time course.")
    normalized = bird_daily.merge(baseline_df, on="animal_id", how="inner")
    valid = normalized["baseline_cv_median"] > 0
    normalized = normalized[valid].copy()
    normalized["cv_fold_change"] = normalized["cv"] / normalized["baseline_cv_median"]
    return normalized, baseline_df


def rolling_equal_bird_summary(
    normalized: pd.DataFrame,
    *,
    x_min: int,
    x_max: int,
    window_days: int,
    min_observations_per_bird_window: int,
    min_birds: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    half = window_days // 2
    bird_rows: list[dict[str, Any]] = []
    for group_name in TIMECOURSE_ORDER:
        group_df = normalized[normalized["pooled_group"] == group_name]
        for day in range(x_min, x_max + 1):
            for bird, bird_df in group_df.groupby("animal_id", sort=True):
                window = bird_df[bird_df["relative_day"].between(day - half, day + half)]
                if day < 0:
                    window = window[window["relative_day"] < 0]
                elif day > 0:
                    window = window[window["relative_day"] > 0]
                else:
                    window = window[window["relative_day"] == 0]
                values = window["cv_fold_change"].dropna().to_numpy(dtype=float)
                if len(values) < min_observations_per_bird_window:
                    continue
                bird_rows.append(
                    {
                        "pooled_group": group_name,
                        "animal_id": bird,
                        "relative_day": day,
                        "rolling_cv_fold_change": float(np.median(values)),
                        "n_observations_in_window": len(values),
                    }
                )
    bird_rolling = pd.DataFrame(bird_rows)
    if bird_rolling.empty:
        return bird_rolling, pd.DataFrame()

    summary_rows = []
    for (group_name, day), group in bird_rolling.groupby(["pooled_group", "relative_day"], sort=True):
        values = group["rolling_cv_fold_change"].dropna().to_numpy(dtype=float)
        if len(values) < min_birds:
            continue
        summary_rows.append(
            {
                "pooled_group": group_name,
                "relative_day": day,
                "n_birds": len(values),
                "median": float(np.median(values)),
                "q25": float(np.percentile(values, 25)),
                "q75": float(np.percentile(values, 75)),
            }
        )
    return bird_rolling, pd.DataFrame(summary_rows)


def plot_cv_timecourse(
    summary: pd.DataFrame,
    path: Path,
    *,
    colors: Mapping[str, str],
    x_min: int,
    x_max: int,
    y_min: Optional[float],
    y_max: Optional[float],
    dpi: int,
    show: bool,
) -> Path:
    if summary.empty:
        raise ValueError("The rolling time-course summary was empty.")
    fig, ax = plt.subplots(figsize=(7.4, 4.8))
    labels = {
        POOLED_ML_GROUP: "Complete and partial\nmedial+lateral lesion",
        SHAM_GROUP: "Sham saline injection",
    }
    for group in TIMECOURSE_ORDER:
        group_df = summary[summary["pooled_group"] == group].sort_values("relative_day")
        if group_df.empty:
            continue
        x = group_df["relative_day"].to_numpy(dtype=float)
        med = group_df["median"].to_numpy(dtype=float)
        q25 = group_df["q25"].to_numpy(dtype=float)
        q75 = group_df["q75"].to_numpy(dtype=float)
        color = colors.get(group, DEFAULT_COLORS[UNKNOWN_GROUP])
        ax.fill_between(x, q25, q75, color=color, alpha=0.18, linewidth=0)
        ax.plot(x, med, color=color, linewidth=3.0, label=labels[group])

    ax.axhline(1.0, color="0.45", linestyle=":", linewidth=1.0)
    ax.axvline(0, color=LESION_DAY_COLOR, linestyle="--", linewidth=1.3)
    ax.set_xlim(x_min, x_max)
    ax.set_xlabel("Days relative to lesion", fontsize=17)
    ax.set_ylabel("Phrase duration CV\n/ late-pre baseline", fontsize=17)
    pretty_axes(ax, tick_size=13)
    ax.yaxis.set_major_formatter(FuncFormatter(plain_number))

    if y_min is None or y_max is None:
        values = np.concatenate([
            summary["q25"].dropna().to_numpy(dtype=float),
            summary["q75"].dropna().to_numpy(dtype=float),
            np.asarray([1.0]),
        ])
        automatic_low, automatic_high = np.percentile(values, [1, 99])
        span = max(float(automatic_high - automatic_low), 0.10)
        low = automatic_low - 0.06 * span if y_min is None else y_min
        high = automatic_high + 0.08 * span if y_max is None else y_max
        ax.set_ylim(low, high)
    else:
        ax.set_ylim(y_min, y_max)

    handles = [
        Line2D([0], [0], color=colors[POOLED_ML_GROUP], linewidth=3.0, label=labels[POOLED_ML_GROUP]),
        Line2D([0], [0], color=colors[SHAM_GROUP], linewidth=3.0, label=labels[SHAM_GROUP]),
        Patch(facecolor="0.75", edgecolor="none", alpha=0.35, label="IQR across birds"),
        Line2D([0], [0], color=LESION_DAY_COLOR, linestyle="--", linewidth=1.3, label="lesion/injection day"),
    ]
    ax.legend(handles=handles, frameon=False, fontsize=10.5, loc="upper left")
    fig.subplots_adjust(left=0.19, right=0.98, bottom=0.17, top=0.98)
    return save_png(fig, path, dpi, show)


# -----------------------------------------------------------------------------
# Summary writer
# -----------------------------------------------------------------------------
def write_summary(
    path: Path,
    *,
    selected: pd.DataFrame,
    audit: pd.DataFrame,
    syllable_metrics: pd.DataFrame,
    bird_metrics: pd.DataFrame,
    tests: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    lines = [
        "Figure 3 upper-fraction CV panel summary",
        "=========================================",
        "",
        f"Target fraction: {args.top_fraction}",
        "Selection rule: ceil(target fraction × eligible syllables)",
        f"Ranking metric: {args.rank_on}",
        f"Period windows: {args.pre_start_day} to {args.pre_end_day} (late pre); "
        f"{args.post_start_day} to {args.post_end_day} (post)",
        f"Equal-count balancing draws: {args.balance_draws}",
        f"Birds selected from scatter table: {selected['animal_id'].nunique() if not selected.empty else 0}",
        f"Selected animal × syllable pairs: {len(selected)}",
        f"Pairs with usable balanced CV metrics: {len(syllable_metrics)}",
        f"Birds with usable bird-level ΔCV: {len(bird_metrics)}",
        "",
        "Selection counts by group",
        "-------------------------",
    ]
    if audit.empty:
        lines.append("No selection audit rows.")
    else:
        for group, group_df in audit.groupby("display_group", sort=False):
            lines.append(
                f"{group}: n={len(group_df)} birds; median selected="
                f"{group_df['n_selected_syllables'].median():.1f}; range="
                f"{int(group_df['n_selected_syllables'].min())}–{int(group_df['n_selected_syllables'].max())}"
            )
    lines += ["", "Pairwise exact bird-label permutation tests", "-------------------------------------------"]
    if tests.empty:
        lines.append("No tests were available.")
    else:
        for _, row in tests.iterrows():
            lines.append(
                f"{row['group1']} vs {row['group2']}: difference={row['mean_difference_group1_minus_group2']:.6g}; "
                f"one-sided p={row['p_one_sided']:.6g}; Holm p={row['p_one_sided_holm']:.6g}; "
                f"95% bootstrap CI=[{row['bootstrap_ci_low']:.6g}, {row['bootstrap_ci_high']:.6g}]"
            )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# -----------------------------------------------------------------------------
# CLI and main workflow
# -----------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
        description="Create Figure 3 top-15% SD scatter, ΔCV boxplot, and CV time course as PNGs.",
    )
    parser.add_argument("--scatter-csv", type=Path, required=True)
    parser.add_argument("--duration-long-csv", type=Path, required=True)
    parser.add_argument(
        "--metadata-excel",
        type=Path,
        default=None,
        help=(
            "Optional metadata workbook. When omitted, lesion groups and surgery dates "
            "are read from lesion_group and lesion_surgery_date columns in the generated CSVs."
        ),
    )
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--color-json", type=Path, default=None)

    parser.add_argument("--top-fraction", type=float, default=0.15)
    parser.add_argument("--rank-on", choices=["pre", "post", "max", "pooled"], default="pooled")
    parser.add_argument("--pre-group", default="Late Pre")
    parser.add_argument("--post-group", default="Post")
    parser.add_argument("--pre-start-day", type=int, default=-14)
    parser.add_argument("--pre-end-day", type=int, default=-1)
    parser.add_argument("--post-start-day", type=int, default=1)
    parser.add_argument("--post-end-day", type=int, default=14)
    parser.add_argument("--x-min", type=int, default=-30)
    parser.add_argument("--x-max", type=int, default=30)

    parser.add_argument("--min-scatter-phrases", type=int, default=5)
    parser.add_argument("--min-period-phrases", type=int, default=10)
    parser.add_argument("--min-period-days", type=int, default=2)
    parser.add_argument("--balance-draws", type=int, default=200)
    parser.add_argument("--min-daily-phrases", type=int, default=5)
    parser.add_argument("--min-baseline-days", type=int, default=3)
    parser.add_argument("--smooth-window-days", type=int, default=7)
    parser.add_argument("--min-observations-per-bird-window", type=int, default=1)
    parser.add_argument("--min-birds-for-summary", type=int, default=3)

    parser.add_argument("--duration-unit", choices=["auto", "ms", "s"], default="auto")
    parser.add_argument("--metadata-sheet", default=None)
    parser.add_argument("--metadata-animal-col", default=None)
    parser.add_argument("--metadata-hit-col", default=None)
    parser.add_argument("--metadata-date-col", default=None)

    parser.add_argument("--scatter-animal-col", default=None)
    parser.add_argument("--scatter-syllable-col", default=None)
    parser.add_argument("--scatter-group-col", default=None)
    parser.add_argument("--scatter-variance-col", default=None)
    parser.add_argument("--scatter-n-col", default=None)

    parser.add_argument("--long-animal-col", default=None)
    parser.add_argument("--long-syllable-col", default=None)
    parser.add_argument("--long-duration-col", default=None)
    parser.add_argument("--long-day-col", default=None)
    parser.add_argument("--long-date-col", default=None)
    parser.add_argument("--long-period-col", default=None)

    parser.add_argument("--seed", type=int, default=123)
    parser.add_argument("--bootstrap-reps", type=int, default=5000)
    parser.add_argument("--max-exact-permutations", type=int, default=200000)
    parser.add_argument("--monte-carlo-permutations", type=int, default=10000)
    parser.add_argument("--annotation-style", choices=["stars", "p"], default="stars")
    parser.add_argument("--timecourse-y-min", type=float, default=None)
    parser.add_argument("--timecourse-y-max", type=float, default=None)
    parser.add_argument("--dpi", type=int, default=300)
    parser.add_argument("--show", action="store_true")
    parser.add_argument("--no-show", action="store_true")
    return parser


def validate_args(args: argparse.Namespace) -> None:
    if not 0 < args.top_fraction <= 1:
        raise ValueError("--top-fraction must be in (0, 1].")
    if args.balance_draws < 1:
        raise ValueError("--balance-draws must be at least 1.")
    if args.smooth_window_days < 1:
        raise ValueError("--smooth-window-days must be at least 1.")
    if args.x_min >= args.x_max:
        raise ValueError("--x-min must be less than --x-max.")
    for path in [args.scatter_csv, args.duration_long_csv]:
        if not path.exists():
            raise FileNotFoundError(path)
    if args.metadata_excel is not None and not args.metadata_excel.exists():
        raise FileNotFoundError(args.metadata_excel)


def main() -> None:
    args = build_parser().parse_args()
    validate_args(args)
    show = bool(args.show and not args.no_show)
    out_dir = ensure_dir(args.out_dir)
    colors = load_colors(args.color_json)

    hit_map, treatment_dates = load_metadata(
        args.metadata_excel,
        preferred_sheet=args.metadata_sheet,
        animal_col_requested=args.metadata_animal_col,
        hit_col_requested=args.metadata_hit_col,
        date_col_requested=args.metadata_date_col,
    )
    if not hit_map:
        print("[INFO] No metadata workbook supplied; lesion groups will be read from the generated CSV columns.")

    selected, audit = prepare_selected_scatter(
        args.scatter_csv,
        hit_map=hit_map,
        top_fraction=args.top_fraction,
        rank_on=args.rank_on,
        pre_group=args.pre_group,
        post_group=args.post_group,
        min_n_phrases=args.min_scatter_phrases,
        animal_col_requested=args.scatter_animal_col,
        syllable_col_requested=args.scatter_syllable_col,
        group_col_requested=args.scatter_group_col,
        variance_col_requested=args.scatter_variance_col,
        n_col_requested=args.scatter_n_col,
    )
    if selected.empty:
        raise ValueError("No eligible bird × syllable pairs were selected from the scatter CSV.")
    if selected["display_group"].eq(UNKNOWN_GROUP).all():
        raise ValueError(
            "No lesion-group labels were found. Supply --metadata-excel or ensure the generated CSVs "
            "contain a lesion_group column."
        )
    selected.to_csv(out_dir / "top15_selected_syllables_and_scatter_metrics.csv", index=False)
    audit.to_csv(out_dir / "top15_selection_audit_by_bird.csv", index=False)
    selected[["animal_id", "syllable"]].to_csv(out_dir / "top15_selected_animal_syllable_pairs.csv", index=False)

    plot_sd_scatter(
        selected,
        out_dir / "Figure3_top15_SD_scatter.png",
        colors=colors,
        dpi=args.dpi,
        show=show,
    )
    save_scatter_legend(out_dir / "Figure3_top15_lesion_group_legend.png", colors, args.dpi)

    long_df = prepare_long_table(
        args.duration_long_csv,
        hit_map=hit_map,
        treatment_dates=treatment_dates,
        duration_unit=args.duration_unit,
        animal_col_requested=args.long_animal_col,
        syllable_col_requested=args.long_syllable_col,
        duration_col_requested=args.long_duration_col,
        day_col_requested=args.long_day_col,
        date_col_requested=args.long_date_col,
        period_col_requested=args.long_period_col,
    )
    long_df = assign_analysis_periods(
        long_df,
        pre_group=args.pre_group,
        post_group=args.post_group,
        pre_start_day=args.pre_start_day,
        pre_end_day=args.pre_end_day,
        post_start_day=args.post_start_day,
        post_end_day=args.post_end_day,
    )

    syllable_metrics = calculate_selected_cv_metrics(
        long_df,
        selected,
        min_period_phrases=args.min_period_phrases,
        min_period_days=args.min_period_days,
        balance_draws=args.balance_draws,
        seed=args.seed,
    )
    if syllable_metrics.empty:
        raise ValueError(
            "No selected syllables had enough late-pre and post phrase occurrences for balanced CV metrics."
        )
    syllable_metrics.to_csv(out_dir / "top15_animal_syllable_balanced_CV_metrics.csv", index=False)

    bird_metrics = bird_level_cv_table(syllable_metrics)
    bird_metrics.to_csv(out_dir / "top15_bird_level_delta_CV.csv", index=False)
    tests = run_pairwise_tests(
        bird_metrics,
        seed=args.seed,
        bootstrap_reps=args.bootstrap_reps,
        max_exact=args.max_exact_permutations,
        monte_carlo_reps=args.monte_carlo_permutations,
    )
    tests.to_csv(out_dir / "top15_pairwise_exact_permutation_tests.csv", index=False)
    plot_delta_cv_boxplot(
        bird_metrics,
        tests,
        out_dir / "Figure3_top15_delta_CV_boxplot.png",
        colors=colors,
        annotation_style=args.annotation_style,
        dpi=args.dpi,
        show=show,
    )

    daily_syllable, bird_daily = calculate_daily_cv(
        long_df,
        selected,
        min_daily_phrases=args.min_daily_phrases,
        x_min=args.x_min,
        x_max=args.x_max,
    )
    daily_syllable.to_csv(out_dir / "top15_daily_CV_by_bird_syllable.csv", index=False)
    bird_daily.to_csv(out_dir / "top15_daily_CV_by_bird.csv", index=False)
    normalized, baseline = normalize_to_late_pre(
        bird_daily,
        baseline_start=args.pre_start_day,
        baseline_end=args.pre_end_day,
        min_baseline_days=args.min_baseline_days,
    )
    normalized.to_csv(out_dir / "top15_daily_CV_by_bird_normalized.csv", index=False)
    baseline.to_csv(out_dir / "top15_CV_baseline_summary_by_bird.csv", index=False)
    bird_rolling, rolling_summary = rolling_equal_bird_summary(
        normalized,
        x_min=args.x_min,
        x_max=args.x_max,
        window_days=args.smooth_window_days,
        min_observations_per_bird_window=args.min_observations_per_bird_window,
        min_birds=args.min_birds_for_summary,
    )
    bird_rolling.to_csv(out_dir / "top15_CV_equal_bird_rolling_values.csv", index=False)
    rolling_summary.to_csv(out_dir / "top15_CV_equal_bird_rolling_summary.csv", index=False)
    plot_cv_timecourse(
        rolling_summary,
        out_dir / "Figure3_top15_CV_rolling_timecourse.png",
        colors=colors,
        x_min=args.x_min,
        x_max=args.x_max,
        y_min=args.timecourse_y_min,
        y_max=args.timecourse_y_max,
        dpi=args.dpi,
        show=show,
    )

    summary_path = out_dir / "top15_figure3_analysis_summary.txt"
    write_summary(
        summary_path,
        selected=selected,
        audit=audit,
        syllable_metrics=syllable_metrics,
        bird_metrics=bird_metrics,
        tests=tests,
        args=args,
    )

    print("[OK] PNG panels written:")
    for name in [
        "Figure3_top15_SD_scatter.png",
        "Figure3_top15_delta_CV_boxplot.png",
        "Figure3_top15_CV_rolling_timecourse.png",
        "Figure3_top15_lesion_group_legend.png",
    ]:
        print(f"  {out_dir / name}")
    print(f"[OK] Tables and summary written to: {out_dir}")


if __name__ == "__main__":
    main()
