#!/usr/bin/env python3
"""
phrase_duration_sd_resampling_supplemental_table_v1.py

Build reviewer-facing phrase-duration robustness tables and figures from the
animal x syllable pre/post SD tables already produced by the AFP lesion pipeline.

This script is meant to address three reviewer/statistics concerns using the
currently available *aggregated* CSVs:

1) Supplemental Table 1
   - one clean group-summary table, one contrast table, and one animal-level table
   - rows can be pasted into the supplemental document

2) Direct medial+lateral vs. lateral-only contrast
   - label-shuffle permutation test at the bird level
   - optional secondary contrasts versus sham

3) Bootstrap CI version of the SD-change result
   - nonparametric bird-level bootstrap confidence intervals for group medians
   - nonparametric bootstrap confidence intervals for between-group differences

Important limitation
--------------------
The CSVs this script consumes already contain pre_sd_ms and post_sd_ms for each
animal x syllable. That means the rendition-level variation has already been
collapsed. Therefore this script performs bird-level bootstrap/permutation
statistics, not the full two-level rendition-within-bird hierarchical bootstrap.
For a true rendition-level hierarchical bootstrap and held-out post-lesion
selection, you need a long-format table with one row per phrase rendition. The
script still includes table fields for "selection_basis" so you can pass in
separate pre-selected / pooled-selected / held-out-selected CSVs generated by
upstream code.

Expected input CSV columns
--------------------------
Required:
    Animal ID, Syllable, pre_sd_ms, post_sd_ms, delta_sd_ms, hit_type
Optional but useful:
    pre_n_phrases, post_n_phrases, lesion_pct, lesion_pct_avg, treatment_group

Typical usage on the current uploaded top-30% post-selected table
----------------------------------------------------------------
python phrase_duration_sd_resampling_supplemental_table_v1.py \
  --analysis "Post-selected top 30%" \
             "/Volumes/my_own_SSD/updated_AreaX_outputs/pre_post_sd_scatter_paper_format_v9/pre_post_sd_table__pre_Late_Pre__post_Post__topP70_post.csv" \
  --out-dir "/Volumes/my_own_SSD/updated_AreaX_outputs/phrase_duration_resampling_tables_v1" \
  --n-bootstrap 5000 \
  --n-permutations 10000 \
  --stat median \
  --alternative greater

Typical usage with multiple selection-validation CSVs
-----------------------------------------------------
python phrase_duration_sd_resampling_supplemental_table_v1.py \
  --analysis "Post-selected top 20%" path/to/pre_post_sd_topP80_post.csv \
  --analysis "Post-selected top 30%" path/to/pre_post_sd_topP70_post.csv \
  --analysis "Post-selected top 40%" path/to/pre_post_sd_topP60_post.csv \
  --analysis "Pooled pre+post-selected top 30%" path/to/pre_post_sd_topP70_pooled.csv \
  --analysis "Pre-selected top 30% validation" path/to/pre_post_sd_topP70_pre.csv \
  --out-dir path/to/out

Outputs
-------
Supplemental_Table_1_group_summary.csv
Supplemental_Table_1_pairwise_contrasts.csv
Supplemental_Table_1_animal_level.csv
Supplemental_Table_1_combined_for_copy_paste.csv
phrase_duration_delta_bootstrap_contrast_<label>.png/.pdf
"""

from __future__ import annotations

import argparse
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# Manuscript group labels
SHAM = "sham saline injection"
LATERAL = "Lateral lesion only"
PARTIAL_ML = "Partial Medial and Lateral lesion"
COMPLETE_ML = "Complete Medial and Lateral lesion"
POOLED_ML = "Complete and partial medial and lateral lesion"

GROUP_ORDER = [SHAM, LATERAL, PARTIAL_ML, COMPLETE_ML, POOLED_ML]
PLOT_GROUP_ORDER = [SHAM, LATERAL, POOLED_ML]

COLOR_MAP = {
    SHAM: "#1FA187",
    LATERAL: "#B39DDB",
    PARTIAL_ML: "#7E57C2",
    COMPLETE_ML: "#4A148C",
    POOLED_ML: "#5E35B1",
}

CONTRASTS = [
    # This is the key anatomical-specificity contrast.
    (POOLED_ML, LATERAL, "primary specificity: medial+lateral > lateral-only"),
    # Secondary controls.
    (POOLED_ML, SHAM, "secondary control: medial+lateral > sham"),
    (LATERAL, SHAM, "secondary control: lateral-only > sham"),
]


@dataclass
class AnalysisInput:
    label: str
    path: Path


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Generate Supplemental Table 1 and bird-level bootstrap/permutation "
            "statistics for phrase-duration SD changes."
        )
    )
    p.add_argument(
        "--analysis",
        nargs=2,
        action="append",
        metavar=("LABEL", "PREPOST_CSV"),
        required=True,
        help=(
            "Analysis label and pre/post SD CSV path. Repeat for top20/top30/top40, "
            "pre-selected validation, held-out validation, etc."
        ),
    )
    p.add_argument("--out-dir", type=Path, required=True, help="Output directory.")
    p.add_argument("--prefix", default="phrase_duration", help="Prefix for figure files.")
    p.add_argument("--seed", type=int, default=12345)
    p.add_argument("--n-bootstrap", type=int, default=5000)
    p.add_argument("--n-permutations", type=int, default=10000)
    p.add_argument(
        "--stat",
        choices=["median", "mean"],
        default="median",
        help="Central statistic for ΔSD summaries and contrasts. Median is robust and matches the current figure text.",
    )
    p.add_argument(
        "--alternative",
        choices=["greater", "two-sided"],
        default="greater",
        help="Permutation alternative. 'greater' tests group A ΔSD > group B ΔSD / ΔSD > 0.",
    )
    p.add_argument(
        "--primary-label",
        default=None,
        help="Analysis label to use for the main delta contrast figure. Default: first --analysis label.",
    )
    p.add_argument("--dpi", type=int, default=300)
    p.add_argument("--show", action="store_true")
    return p.parse_args()


def center(values: Iterable[float], stat: str = "median") -> float:
    arr = np.asarray(list(values), dtype=float)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return np.nan
    if stat == "mean":
        return float(np.mean(arr))
    return float(np.median(arr))


def _safe_float(x) -> float:
    try:
        return float(x)
    except Exception:
        return np.nan


def pvalue_from_null(obs: float, null: np.ndarray, alternative: str) -> float:
    null = np.asarray(null, dtype=float)
    null = null[np.isfinite(null)]
    if not np.isfinite(obs) or null.size == 0:
        return np.nan
    if alternative == "greater":
        count = np.sum(null >= obs)
    elif alternative == "two-sided":
        count = np.sum(np.abs(null) >= abs(obs))
    else:
        raise ValueError(f"Unknown alternative: {alternative}")
    return float((count + 1) / (null.size + 1))


def bootstrap_ci(values: np.ndarray, rng: np.random.Generator, B: int, stat: str) -> tuple[float, float, float]:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if values.size == 0:
        return np.nan, np.nan, np.nan
    obs = center(values, stat=stat)
    boots = np.empty(B, dtype=float)
    n = values.size
    for b in range(B):
        boots[b] = center(rng.choice(values, size=n, replace=True), stat=stat)
    lo, hi = np.percentile(boots, [2.5, 97.5])
    return obs, float(lo), float(hi)


def bootstrap_diff_ci(
    values_a: np.ndarray,
    values_b: np.ndarray,
    rng: np.random.Generator,
    B: int,
    stat: str,
) -> tuple[float, float, float]:
    values_a = np.asarray(values_a, dtype=float)
    values_b = np.asarray(values_b, dtype=float)
    values_a = values_a[np.isfinite(values_a)]
    values_b = values_b[np.isfinite(values_b)]
    if values_a.size == 0 or values_b.size == 0:
        return np.nan, np.nan, np.nan
    obs = center(values_a, stat=stat) - center(values_b, stat=stat)
    boots = np.empty(B, dtype=float)
    for b in range(B):
        sample_a = rng.choice(values_a, size=values_a.size, replace=True)
        sample_b = rng.choice(values_b, size=values_b.size, replace=True)
        boots[b] = center(sample_a, stat=stat) - center(sample_b, stat=stat)
    lo, hi = np.percentile(boots, [2.5, 97.5])
    return float(obs), float(lo), float(hi)


def signflip_test(values: np.ndarray, rng: np.random.Generator, P: int, stat: str, alternative: str) -> tuple[float, float]:
    values = np.asarray(values, dtype=float)
    values = values[np.isfinite(values)]
    if values.size == 0:
        return np.nan, np.nan
    obs = center(values, stat=stat)
    null = np.empty(P, dtype=float)
    n = values.size
    for i in range(P):
        signs = rng.choice(np.array([-1.0, 1.0]), size=n, replace=True)
        null[i] = center(values * signs, stat=stat)
    return float(obs), pvalue_from_null(obs, null, alternative=alternative)


def labelshuffle_test(
    values_a: np.ndarray,
    values_b: np.ndarray,
    rng: np.random.Generator,
    P: int,
    stat: str,
    alternative: str,
) -> tuple[float, float]:
    values_a = np.asarray(values_a, dtype=float)
    values_b = np.asarray(values_b, dtype=float)
    values_a = values_a[np.isfinite(values_a)]
    values_b = values_b[np.isfinite(values_b)]
    if values_a.size == 0 or values_b.size == 0:
        return np.nan, np.nan
    obs = center(values_a, stat=stat) - center(values_b, stat=stat)
    pooled = np.concatenate([values_a, values_b])
    n_a = values_a.size
    null = np.empty(P, dtype=float)
    for i in range(P):
        perm = rng.permutation(pooled)
        null[i] = center(perm[:n_a], stat=stat) - center(perm[n_a:], stat=stat)
    return float(obs), pvalue_from_null(obs, null, alternative=alternative)


def sig_label(p: float) -> str:
    p = _safe_float(p)
    if not np.isfinite(p):
        return "n/a"
    if p < 0.001:
        return "***"
    if p < 0.01:
        return "**"
    if p < 0.05:
        return "*"
    return "n.s."


def method_basis(label: str) -> str:
    s = label.lower()
    if "held" in s:
        return "held-out post-lesion selection"
    if "pre" in s and "post" not in s:
        return "late pre-lesion selection"
    if "pooled" in s or "pre+post" in s or "pre + post" in s:
        return "pooled pre/post selection"
    if "post" in s:
        return "post-lesion selection"
    return "unspecified selection basis"


def method_fraction(label: str) -> str:
    m = re.search(r"(\d+)\s*%", label)
    return f"top {m.group(1)}%" if m else "unspecified"


def normalize_group(row: pd.Series) -> str:
    hit = str(row.get("hit_type", "")).lower()
    treatment = str(row.get("treatment_group", "")).lower()
    plot_group = str(row.get("lesion_group_for_plot", "")).lower()

    if "sham" in hit or treatment == "sham" or "sham" in plot_group:
        return SHAM
    # In current metadata, visible single hits are lateral-only hits.
    if "single hit" in hit or "lateral" in hit and "medial" not in hit:
        return LATERAL
    if "medial+lateral" in hit or "medial and lateral" in hit:
        return PARTIAL_ML
    # Large Area X not visible lesions are treated as complete medial+lateral lesions.
    if "not visible" in hit or "complete" in plot_group:
        return COMPLETE_ML
    # Fallback for already-pooled labels if an upstream file has them.
    if "partial" in plot_group:
        return PARTIAL_ML
    if "lateral" in plot_group and "medial" not in plot_group:
        return LATERAL
    return "unclassified"


def add_pooled_ml_rows(df: pd.DataFrame) -> pd.DataFrame:
    pooled = df[df["lesion_group"].isin([PARTIAL_ML, COMPLETE_ML])].copy()
    if pooled.empty:
        return df
    pooled["lesion_group"] = POOLED_ML
    return pd.concat([df, pooled], ignore_index=True)


def load_prepost_table(path: Path, label: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    df = pd.read_csv(path)
    required = ["Animal ID", "Syllable", "pre_sd_ms", "post_sd_ms"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{path} is missing required columns: {missing}")

    df = df.copy()
    if "delta_sd_ms" not in df.columns:
        df["delta_sd_ms"] = df["post_sd_ms"] - df["pre_sd_ms"]
    if "hit_type" not in df.columns:
        df["hit_type"] = ""

    df["selection_method"] = label
    df["selection_basis"] = method_basis(label)
    df["selection_fraction"] = method_fraction(label)
    df["lesion_group_base"] = df.apply(normalize_group, axis=1)
    df["lesion_group"] = df["lesion_group_base"]

    numeric_cols = [
        "pre_sd_ms", "post_sd_ms", "delta_sd_ms", "pre_n_phrases", "post_n_phrases",
        "lesion_pct", "lesion_pct_avg",
    ]
    for col in numeric_cols:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    df = df.replace([np.inf, -np.inf], np.nan)
    df = df[df["lesion_group"].isin([SHAM, LATERAL, PARTIAL_ML, COMPLETE_ML])].copy()

    # Animal-level values. The current figure text uses the median across retained syllables.
    agg_dict = {
        "n_syllables": ("Syllable", "nunique"),
        "median_pre_sd_ms": ("pre_sd_ms", "median"),
        "median_post_sd_ms": ("post_sd_ms", "median"),
        "median_delta_sd_ms": ("delta_sd_ms", "median"),
        "mean_delta_sd_ms": ("delta_sd_ms", "mean"),
    }
    if "pre_n_phrases" in df.columns:
        agg_dict.update({
            "total_pre_phrases": ("pre_n_phrases", "sum"),
            "median_pre_phrases_per_syllable": ("pre_n_phrases", "median"),
        })
    if "post_n_phrases" in df.columns:
        agg_dict.update({
            "total_post_phrases": ("post_n_phrases", "sum"),
            "median_post_phrases_per_syllable": ("post_n_phrases", "median"),
        })
    if "lesion_pct" in df.columns:
        agg_dict["lesion_pct"] = ("lesion_pct", "median")
    if "lesion_pct_avg" in df.columns:
        agg_dict["lesion_pct_avg"] = ("lesion_pct_avg", "median")

    animal = (
        df.groupby(["selection_method", "selection_basis", "selection_fraction", "Animal ID", "lesion_group"], dropna=False)
        .agg(**agg_dict)
        .reset_index()
    )
    animal = add_pooled_ml_rows(animal)
    return df, animal


def make_group_summary(animal: pd.DataFrame, rng: np.random.Generator, B: int, P: int, stat: str, alternative: str) -> pd.DataFrame:
    rows = []
    for (method, basis, fraction, group), g in animal.groupby(
        ["selection_method", "selection_basis", "selection_fraction", "lesion_group"], dropna=False
    ):
        values = g["median_delta_sd_ms"].to_numpy(dtype=float)
        obs, lo, hi = bootstrap_ci(values, rng, B=B, stat=stat)
        _, p_sign = signflip_test(values, rng, P=P, stat=stat, alternative=alternative)
        rows.append({
            "selection_method": method,
            "selection_basis": basis,
            "selection_fraction": fraction,
            "lesion_group": group,
            "n_birds": int(g["Animal ID"].nunique()),
            "total_selected_syllables": int(g["n_syllables"].sum()),
            "median_selected_syllables_per_bird": center(g["n_syllables"], stat="median"),
            "median_late_pre_SD_ms": center(g["median_pre_sd_ms"], stat=stat),
            "median_post_SD_ms": center(g["median_post_sd_ms"], stat=stat),
            f"{stat}_delta_SD_ms": obs,
            "delta_SD_bootstrap_CI95_low_ms": lo,
            "delta_SD_bootstrap_CI95_high_ms": hi,
            f"signflip_p_delta_gt_0_{alternative}": p_sign,
            "significance": sig_label(p_sign),
            "resampling_level": "bird-level aggregate",
        })
    out = pd.DataFrame(rows)
    out["_group_order"] = out["lesion_group"].map({g: i for i, g in enumerate(GROUP_ORDER)}).fillna(99)
    return out.sort_values(["selection_method", "_group_order"]).drop(columns="_group_order")


def make_contrast_summary(animal: pd.DataFrame, rng: np.random.Generator, B: int, P: int, stat: str, alternative: str) -> pd.DataFrame:
    rows = []
    for (method, basis, fraction), method_df in animal.groupby(["selection_method", "selection_basis", "selection_fraction"], dropna=False):
        for group_a, group_b, contrast_type in CONTRASTS:
            a = method_df.loc[method_df["lesion_group"] == group_a, "median_delta_sd_ms"].to_numpy(dtype=float)
            b = method_df.loc[method_df["lesion_group"] == group_b, "median_delta_sd_ms"].to_numpy(dtype=float)
            diff, lo, hi = bootstrap_diff_ci(a, b, rng, B=B, stat=stat)
            _, p_perm = labelshuffle_test(a, b, rng, P=P, stat=stat, alternative=alternative)
            rows.append({
                "selection_method": method,
                "selection_basis": basis,
                "selection_fraction": fraction,
                "contrast_type": contrast_type,
                "group_A": group_a,
                "group_B": group_b,
                "n_A_birds": int(np.isfinite(a).sum()),
                "n_B_birds": int(np.isfinite(b).sum()),
                f"observed_{stat}_delta_difference_ms_A_minus_B": diff,
                "difference_bootstrap_CI95_low_ms": lo,
                "difference_bootstrap_CI95_high_ms": hi,
                f"labelshuffle_p_A_gt_B_{alternative}": p_perm,
                "significance": sig_label(p_perm),
                "resampling_level": "bird-level aggregate",
            })
    return pd.DataFrame(rows)


def combined_copy_paste_table(group_summary: pd.DataFrame, contrasts: pd.DataFrame) -> pd.DataFrame:
    group_rows = group_summary.copy()
    group_rows.insert(0, "table_section", "group summary")
    group_rows["comparison"] = group_rows["lesion_group"]

    contrast_rows = contrasts.copy()
    contrast_rows.insert(0, "table_section", "pairwise contrast")
    contrast_rows["comparison"] = contrast_rows["group_A"] + " vs " + contrast_rows["group_B"]

    # Common display columns first, then keep everything else.
    common = [
        "table_section", "selection_method", "selection_basis", "selection_fraction", "comparison",
        "n_birds", "n_A_birds", "n_B_birds", "total_selected_syllables",
        "median_selected_syllables_per_bird", "median_late_pre_SD_ms", "median_post_SD_ms",
        "median_delta_SD_ms", "mean_delta_SD_ms",
        "delta_SD_bootstrap_CI95_low_ms", "delta_SD_bootstrap_CI95_high_ms",
        "observed_median_delta_difference_ms_A_minus_B", "observed_mean_delta_difference_ms_A_minus_B",
        "difference_bootstrap_CI95_low_ms", "difference_bootstrap_CI95_high_ms",
        "significance", "resampling_level",
    ]
    all_cols = []
    tmp = pd.concat([group_rows, contrast_rows], ignore_index=True, sort=False)
    for c in common:
        if c in tmp.columns and c not in all_cols:
            all_cols.append(c)
    for c in tmp.columns:
        if c not in all_cols:
            all_cols.append(c)
    return tmp[all_cols]


def sanitize_filename(label: str) -> str:
    s = re.sub(r"[^A-Za-z0-9]+", "_", label).strip("_")
    return s[:80] if s else "analysis"


def add_bracket(ax, x1: float, x2: float, y: float, h: float, text: str, fontsize: int = 11) -> None:
    ax.plot([x1, x1, x2, x2], [y, y + h, y + h, y], color="0.15", linewidth=1.2, clip_on=False)
    ax.text((x1 + x2) / 2, y + h, text, ha="center", va="bottom", fontsize=fontsize)


def plot_primary_delta(
    animal: pd.DataFrame,
    contrasts: pd.DataFrame,
    label: str,
    out_dir: Path,
    prefix: str,
    dpi: int,
    stat: str,
    show: bool = False,
) -> None:
    d = animal[animal["selection_method"] == label].copy()
    if d.empty:
        print(f"[WARN] No rows for primary plot label: {label}")
        return
    d = d[d["lesion_group"].isin(PLOT_GROUP_ORDER)].copy()
    if d.empty:
        print(f"[WARN] No plot groups found for primary plot label: {label}")
        return

    fig, ax = plt.subplots(figsize=(7.8, 5.5))
    rng = np.random.default_rng(123)
    x_positions = {g: i for i, g in enumerate(PLOT_GROUP_ORDER)}

    ymin = np.nanmin(d["median_delta_sd_ms"].to_numpy(dtype=float))
    ymax = np.nanmax(d["median_delta_sd_ms"].to_numpy(dtype=float))
    yrange = max(ymax - ymin, 1.0)

    # Points and CIs.
    for group in PLOT_GROUP_ORDER:
        g = d[d["lesion_group"] == group]
        if g.empty:
            continue
        x = x_positions[group]
        vals = g["median_delta_sd_ms"].to_numpy(dtype=float)
        jitter = rng.normal(0, 0.045, size=len(vals))
        ax.scatter(
            np.full(len(vals), x) + jitter,
            vals,
            s=46,
            color=COLOR_MAP[group],
            alpha=0.85,
            edgecolors="white",
            linewidths=0.5,
            zorder=3,
        )
        obs = center(vals, stat=stat)
        # Use a fresh local RNG so CIs on plot match reproducibly but do not mutate stats RNG.
        _, lo, hi = bootstrap_ci(vals, np.random.default_rng(777 + x), B=3000, stat=stat)
        ax.errorbar(
            [x], [obs], yerr=[[obs - lo], [hi - obs]],
            fmt="o", markersize=7, color="black", ecolor="black", capsize=7,
            elinewidth=1.5, zorder=4,
        )
        ax.hlines(obs, x - 0.22, x + 0.22, color="black", linewidth=2, zorder=4)

    ax.axhline(0, color="0.35", linestyle="--", linewidth=1)
    ax.set_xticks(range(len(PLOT_GROUP_ORDER)))
    ax.set_xticklabels(["Sham", "Lateral AFP\nonly", "Medial+lateral\nAFP"], fontsize=11)
    ax.set_ylabel("Δ phrase-duration SD\n(post-lesion − late pre-lesion, ms)", fontsize=12)
    ax.set_title(f"Animal-level ΔSD with bootstrap CI\n{label}", fontsize=13)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # Main direct specificity contrast: medial+lateral vs lateral-only.
    csub = contrasts[(contrasts["selection_method"] == label)].copy()
    def contrast_p(a, b):
        row = csub[(csub["group_A"] == a) & (csub["group_B"] == b)]
        if row.empty:
            return np.nan
        pcols = [c for c in row.columns if c.startswith("labelshuffle_p_A_gt_B")]
        return float(row.iloc[0][pcols[0]]) if pcols else np.nan

    y_top = ymax + 0.12 * yrange
    h = 0.04 * yrange
    p_ml_lat = contrast_p(POOLED_ML, LATERAL)
    add_bracket(ax, 1, 2, y_top, h, f"ML vs lateral: {sig_label(p_ml_lat)}\np={p_ml_lat:.4g}" if np.isfinite(p_ml_lat) else "ML vs lateral")
    p_ml_sham = contrast_p(POOLED_ML, SHAM)
    if np.isfinite(p_ml_sham):
        add_bracket(ax, 0, 2, y_top + 0.18 * yrange, h, f"ML vs sham: {sig_label(p_ml_sham)}\np={p_ml_sham:.4g}", fontsize=10)

    ax.set_ylim(ymin - 0.15 * yrange, y_top + 0.35 * yrange)
    fig.tight_layout()
    stem = sanitize_filename(label)
    png = out_dir / f"{prefix}_delta_bootstrap_contrast_{stem}.png"
    pdf = out_dir / f"{prefix}_delta_bootstrap_contrast_{stem}.pdf"
    fig.savefig(png, dpi=dpi, bbox_inches="tight")
    fig.savefig(pdf, bbox_inches="tight")
    if show:
        plt.show()
    plt.close(fig)
    print(f"Wrote figure:\n  {png}\n  {pdf}")


def round_for_csv(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    for col in out.columns:
        if pd.api.types.is_float_dtype(out[col]):
            out[col] = out[col].round(6)
    return out


def main() -> None:
    args = parse_args()
    out_dir = args.out_dir.expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    analyses = [AnalysisInput(label=a[0], path=Path(a[1]).expanduser().resolve()) for a in args.analysis]

    all_syllable_rows = []
    all_animal_rows = []
    for a in analyses:
        print(f"Loading {a.label}: {a.path}")
        syllable_df, animal_df = load_prepost_table(a.path, a.label)
        all_syllable_rows.append(syllable_df)
        all_animal_rows.append(animal_df)

    syllable_all = pd.concat(all_syllable_rows, ignore_index=True)
    animal_all = pd.concat(all_animal_rows, ignore_index=True)

    group_summary = make_group_summary(
        animal_all, rng=rng, B=args.n_bootstrap, P=args.n_permutations,
        stat=args.stat, alternative=args.alternative,
    )
    contrasts = make_contrast_summary(
        animal_all, rng=rng, B=args.n_bootstrap, P=args.n_permutations,
        stat=args.stat, alternative=args.alternative,
    )
    combined = combined_copy_paste_table(group_summary, contrasts)

    # Write outputs.
    paths = {
        "group_summary": out_dir / "Supplemental_Table_1_group_summary.csv",
        "pairwise_contrasts": out_dir / "Supplemental_Table_1_pairwise_contrasts.csv",
        "animal_level": out_dir / "Supplemental_Table_1_animal_level.csv",
        "combined": out_dir / "Supplemental_Table_1_combined_for_copy_paste.csv",
        "syllable_level_input_with_groups": out_dir / "Supplemental_Table_1_syllable_level_input_with_groups.csv",
    }
    round_for_csv(group_summary).to_csv(paths["group_summary"], index=False)
    round_for_csv(contrasts).to_csv(paths["pairwise_contrasts"], index=False)
    round_for_csv(animal_all).to_csv(paths["animal_level"], index=False)
    round_for_csv(combined).to_csv(paths["combined"], index=False)
    round_for_csv(syllable_all).to_csv(paths["syllable_level_input_with_groups"], index=False)

    print("\nWrote tables:")
    for p in paths.values():
        print(f"  {p}")

    primary_label = args.primary_label if args.primary_label is not None else analyses[0].label
    plot_primary_delta(
        animal_all, contrasts, primary_label, out_dir, args.prefix, args.dpi,
        stat=args.stat, show=args.show,
    )

    print("\nKey primary contrast rows:")
    key = contrasts[contrasts["contrast_type"].str.contains("primary", na=False)]
    if not key.empty:
        print(round_for_csv(key).to_string(index=False))
    print("\nDone.")


if __name__ == "__main__":
    main()
